### ISSUE TITLE
Using cljfmt within clojure

### ISSUE THREAD

**Issue by lincoln-b** [weavejester/cljfmt#103]
This is a great tool!

I'm wondering if I can use it inside of my project as a dependency.

I tried to do the following:

```
(def form '(ns guestbook.core (:require [guestbook.handler :as handler] [luminus.repl-server :as repl] [luminus.http-server :as http] [luminus-migrations.core :as migrations] [guestbook.config :refer [env]] [clojure.tools.cli :refer [parse-opts]] [clojure.tools.logging :as log] [luminus.logger :as logger] [mount.core :as mount]) (:gen-class)))

(require '[cljfmt.core :as c])
(c/reformat-string (str form))
```

But it's not returning a correctly formatted string. What am I doing wrong?

**Comment by weavejester** [comment]
cljfmt is designed to correct formatting mistakes, not to reformat Clojure code from scratch. Putting all your Clojure code on one line isn't technically incorrect, after all! It sounds like you want [zprint](https://github.com/kkinnear/zprint), an alternative project that will format completely unformatted Clojure code.

**Comment by lincoln-b** [comment]
Oh, ok! Thanks for the clarification. Not sure how I missed that.
