### ISSUE TITLE
Mulitple arity implementations of a protocol inconsistently indented

### ISSUE THREAD

**Issue by vemv** [weavejester/cljfmt#107]
Hi!

cljfmt emits this as formatted code:

```clojure
  ILookup
  (-lookup ([this k]
            (-lookup this k nil))
    ([this k not-found]
     (foo this k not-found)))
```

There's an indentation inconsistency between each arity implementation.

Hope this can get fixed at some point!

Thanks - Victor

**Comment by or** [comment]
This appears to be fixed. I can't reproduce it with 0.6.0+.
