### ISSUE TITLE
Namespaces not preventing collisions with built-in formatters

### ISSUE THREAD

**Issue by MatthewDarling** [weavejester/cljfmt#108]
Given [identical formatting definitions](https://github.com/MatthewDarling/cljfmt-defrecord-formatting-example/blob/master/project.clj#L8-L9) of `[[:block 1] [:inner 1]]`, a form that [shares a name with `clojure.core` will indent differently](https://github.com/MatthewDarling/cljfmt-defrecord-formatting-example/blob/master/src/core.clj):

```clojure
(s/defrecord Complicated
             [attr1 attr2 attr3 attr4
              attr5 attr6 attr7 attr8]
  component/Lifecycle
  (start [component]
    component)
  (stop [component]
    component))

(defcomponent empty-component
  [_ owner _]
  (:mixins [])

  (init-state [_]
    {})

  (render-state [_ state]
    (html [:div])))
``` 

I've found that using `^:replace` will get them to indent the same. However, I sort of expected that a namespaced symbol like `s/defrecord` could have different indentation from `clojure.core/defrecord`. Not even at the level of "resolve the `s` alias and check the indentation rules for its fully qualified name", just like, look up the namespaced symbol in the configuration and use whatever is there.

One downside of respecting the namespace would be potentially having configuration like:

```clojure
{s/defrecord [[:block 1] [:inner 1]]
 schema.core/defrecord [[:block 1] [:inner 1]]
 schema/defrecord [[:block 1] [:inner 1]]}
```

But consistent namespace aliases are good practice, so maybe the extra configuration will cause the user to fix the inconsistency :)

**Comment by MatthewDarling** [comment]
As an aside, I think the behaviour of `^:replace` could be clarified a bit in the readme.

Here's a rough attempt:

```markdown
As with Leiningen profiles, you can add metadata hints. If you want 
to override any existing indents, the `:replace` hint will allow that:

    ```clojure
    :cljfmt {:indents ^:replace {cond [[:inner 0]]}}
    ```

If you want to have a clean slate for defining indents, the replace hint 
combined with a greedy regular expression will allow that:

    ```clojure
    :cljfmt {:indents ^:replace {#".*" [[:inner 0]]}}
    ```

From there, you could define indents one at a time to achieve the desired behaviour.
```

----------

Also, it's not clear to me what a regex indent rule does differently from a symbol indent rule. Does that second example override all indents because the regex is applied during the merge, or because it will match every symbol during indenting? If it's the latter, I'm not sure how that behaviour would be guaranteed, if the merged map was:

```clojure
{alt!            [[:block 0]]
 alt!!           [[:block 0]]
 are            [[:block 2]]
 #".*"         [[:inner 0]]
 ... }
```

Both the `are` key and the `#".*"` key would match the symbol `are`. The README says that the regex definition would win, I just don't follow how/why that works.

**Comment by weavejester** [comment]
A regex rule matches all symbols that match the regular expression. A symbol rule matches only the exact symbol. Symbols are matched before patterns, therefore `are` is matched over `#".*"`.

The `:replace` metadata works the same way as normal Leiningen merging metadata. It's not treated specially.

**Comment by MatthewDarling** [comment]
Oh, I see, looks like `^:replace` on the outer map just discards the original map:

```clojure
user> (meta-merge {'alt! [[:block 0]]
                   'alt!! [[:block 0]]
                   'are [[:block 2]]}
                  ^:replace {#".*" [[:block 2]]})
{#".*" [[:block 2]]}
user> (meta-merge {'alt! [[:block 0]]
                   'alt!! [[:block 0]]
                   'are [[:block 2]]}
                  {#".*" ^:replace [[:block 2]]})
{alt! [[:block 0]],
 alt!! [[:block 0]],
 are [[:block 2]],
 #".*" [[:block 2]]}
user> (meta-merge {'alt! [[:block 0]]
                   'alt!! [[:block 0]]
                   'are [[:block 2]]}
                  {'are ^:replace [[:inner 2]]})
{alt! [[:block 0]],
 alt!! [[:block 0]],
 are [[:inner 2]]}
```

I kind of assumed it would act as though every item in the map had the metadata, guess not.

So the example I gave ought to be:

```clojure
:cljfmt {:indents {cond ^:replace [[:inner 0]]}}
```

----------

Anyway, now that I understand some of those extra details, back to the question of namespaces!

This produces the expected indentation:

```clojure
:cljfmt {:indents {defcomponent [[:block 1] [:inner 1]]
                   defrecord ^:replace [[:block 1] [:inner 1]]}}
```

But having `s/defrecord ^:replace [[:block 1] [:inner 1]]` doesn't.

So, I guess that namespaces must be discarded before looking for matching rules (maybe [this function is responsible](https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/core.cljc#L196-L197)?). Would you be okay with changing the behaviour to support namespaced symbols? Based solely on the current alias, just to make things easier.

I've got that working locally, can open a PR if it's a change you're okay with.

**Comment by weavejester** [comment]
Yes, I'd be happy to accept a PR that adds some manner of namespace support. Obviously it can't work in 100% of cases, as that would require evaluating the namespace, but if we assume that the `ns` declaration is the only source of namespaces then we can find and parse it.

**Comment by vemv** [comment]
Issue looks good to close given https://github.com/weavejester/cljfmt/pull/109 is merged?
