### ISSUE TITLE
New lines disappear when `\n\n\n ` between forms

### ISSUE THREAD

**Issue by snoe** [weavejester/cljfmt#118]
When there are at least three newlines followed by a space between two forms, calling `reformat-string` will delete the newlines:
`(cljfmt/reformat-string "a\n\n\n b") => "a b"`

expected:
`(cljfmt/reformat-string "a\n\n\n b") => "a\n\nb"`

**Comment by ProjectFrank** [comment]
was this issue sufficiently addressed in the PR that references it?

**Comment by weavejester** [comment]
Yes, looks like this is fixed.
