### ISSUE TITLE
Single space after `=` instead of default two

### ISSUE THREAD

**Issue by cbcoutinho** [weavejester/cljfmt#122]
I just used `cljfmt` on a clojure test file and saw the following diff output:

```diff
 (deftest readme-test
   (testing "Test the sample data in the README."
     (is (=
-          (find-parent (parse-file "../sample.txt"))
-          "tknk"))))
+         (find-parent (parse-file "../sample.txt"))
+         "tknk"))))
```

I was expecting it to keep the default of two spaces, but apparently indenting after the `=` uses only one space.

**Comment by weavejester** [comment]
Yes, one space is correct according to [the clojure style guide](https://github.com/bbatsov/clojure-style-guide#one-space-indent), and it's also the indentation that Emacs uses.

**Comment by cbcoutinho** [comment]
Oops! My mistake then - thanks for pointing me to the style guide. Closing this issue
