### ISSUE TITLE
formatting ns forms

### ISSUE THREAD

**Issue by expez** [weavejester/cljfmt#13]
For [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) I made the terrible mistake of trying to write my own pretty-printing code to output the newly-cleaned ns form.  This started out as just a few lines of code which worked in 95% of cases, but has now grown to a a huge mess which badly needs to be rewritten, or preferably thrown out altogether. 

Will it ever be in the scope of `cljfmt` to format an ns form nicely?

**Comment by weavejester** [comment]
I don't see why not.

cljfmt can already correct the indentation of an ns form, but doesn't currently order the namespaces or insert linebreaks when necessary. However, both those things would come under formatting in my book.

**Comment by expez** [comment]
Glad to hear you consider this in-scope for `cljfmt`. 

Here's what the `clean-ns` op in [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) does:

* Eliminate :use clauses
* Sort required libraries, imports and vectors of referred symbols
* Rewrite to favor prefix form, e.g. [clojure [string test]] instead of two separate libspecs
* Raise errors if any inconsistencies are found (e.g. a libspec with more than one alias.
* Remove any unused namespaces, referred symbols or imported classes.
* Remove any duplication in the :require and :import form.

In the interest of not duplication any code I researched the following solutions when I needed to format the ns.  Some of this might interest to you:

`clojure.core/pprint` Has a small amount of special handling for pretty-printing the ns form, but not enough.  The relevant code is [here](https://github.com/clojure/clojure/blob/master/src%2Fclj%2Fclojure%2Fpprint%2Fdispatch.clj#L215-L239)

[fipp](https://github.com/brandonbloom/fipp) which is a pretty-printer construction kit didn't work out of the box, but I now regret trying to hack my own code instead of relying on this lib. 

[slamhound](https://github.com/technomancy/slamhound) has its code for pretty-printing the ns form [here](https://github.com/technomancy/slamhound/blob/master/src/slam/hound/prettify.clj).

The rewriting to use prefix form drove some of these issues I had.  I find the prefix form easier to read, but it's a pain to manage manually (which is why I think it isn't used more widely).  I'd like libspecs that aren't vectors to be printed on their own line(s), but breaking at line 80:

```clojure
(:require [clojure data edn xml
           [instant :as inst]
           [pprint :refer [pprint]]])
```

 I'll likely write an op for [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) to call out to `cljfmt` once it's a bit more mature.

**Comment by weavejester** [comment]
I'm not sure how much of that is in scope for cljfmt. Currently it just affects whitespace, and doesn't change the meaning of the source code. If cljfmt were to affect more, I think it would have to be controlled by an optional flag.

**Comment by expez** [comment]
Perhaps I was unclear: I just want `cljfmt` to format the `ns` nicely, the rest `clj-refactor` can handle (like eliminating duplication and rewriting to use prefix form).  I'm hoping that if just dump the entire ns form on a single line `cljfmt` will insert newlines it in a sensible way.

**Comment by weavejester** [comment]
Oh I see. Yes, that's perfectly within scope of cljfmt.

**Comment by bbatsov** [comment]
> I'll likely write an op for clj-refactor to call out to cljfmt once it's a bit more mature.

Actually we might add this directly to CIDER (I can imaged commands like `format-buffer` and `format-region` (or rather `format-form`). `clj-rewrite` deps shouldn't be problematic for most people.

**Comment by expez** [comment]
:+1:

**Comment by bbatsov** [comment]
And now we have cider commands for `cljfmt`. :-) See https://github.com/clojure-emacs/cider/commit/b661d1019980bb4e4452b4c62b5378f901a33e59

The initial support is pretty basic, but will cover the needs of most people.

**Comment by expez** [comment]
Very cool!

**Comment by xpe** [comment]
@expez Is your issue still open? Or has it been resolved?

**Comment by expez** [comment]
@xpe this issue is still open

I've written some refactorings for moving files and directories of clj files for `clj-refactor`.  Right now I parse and update the ns form of all affected namespaces but then I have to use emacs and `clojure-mode` to visit the files afterwards to get right indentation of the ns form.  

Needless to say I'd be quite happy to skip that last step.  Not only because it makes it easier but because the op becomes slow when a large amount of files are affected.

**Comment by expez** [comment]
@weavejester is this likely to get solved?  I realize this isn't the most sexy problem to spend  limited time on :/

**Comment by weavejester** [comment]
When someone submits a pull request for it.

It's not something I personally need, and isn't a bug but a new feature, so it's fairly far down my list of priorities.

**Comment by expez** [comment]
Hi, I see this was closed in a commit that mentions ns sorting.  Has the formatting / pretty-printing (proper indentation, breaking of long lines in sensible places etc) been solved previously?

Many thanks for your tireless and consistent maintenance of you open source projects @weavejester 🙇
