### ISSUE TITLE
Feature: Elastic Tabstops

### ISSUE THREAD

**Issue by dijonkitchen** [weavejester/cljfmt#131]
Can cljfmt utilize [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/)?

**Comment by dijonkitchen** [comment]
Well could it be done with soft tabs? 

Elastic tabstops might be really good for large maps with keys of different lengths so it makes it more readable or comments that line up too.

**Comment by weavejester** [comment]
I'm afraid I have no incentive to implement a non-standard Clojure formatting in cljfmt.

**Comment by dijonkitchen** [comment]
Does it count as non-standard if Clojure can accept any amount of whitespace between map items?

**Comment by weavejester** [comment]
Just because the syntax is valid doesn't mean it's idiomatic, and cljfmt is designed to produce idiomatic formatting of Clojure.
