### ISSUE TITLE
Calva Formatter is a good choice of clj-fmt for VS Code 

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#139]
Hello,

I notice that the README mentions `vscode-clj-fmt`, but really think that [Calva Clojure Formatter](https://github.com/BetterThanTomorrow/calva-fmt) would be a better choice. It is built from `vscode-clj-fmt` and fixes its bugs while also adding more support for format-as-you-type. It is also bundled with [Calva](https://github.com/BetterThanTomorrow/calva), and lots of people might end up having both formatters installed which would be quite confusing and probably make things work strangely.

I'm pretty sure @pedrorgirardi would agree with me that it is better to point people at Calva Formatter.

**Comment by weavejester** [comment]
Sure, you can add a link to Calva to the README if you want.

**Comment by pedrorgirardi** [comment]
@PEZ, you can remove the link to **vscode-cljfmt** if you think it causes confusion to **Calva** users.
