### ISSUE TITLE
Some lines with only a closing bracket get no indent at all, when not removing surrounding whitespace

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#141]
I'm using `cljfmt/reformat-string` with this option map:

```clojure
{:remove-surrounding-whitespace? false}
```

Formatting:
```clojure
(foo
(bar
)
)
```

I expect:
```clojure
(foo
 (bar
  )
 )
```

But I get:
```clojure
(foo
 (bar
)
 )
```

Am I misunderstanding something or is my expectation correct?

Formatting:
```clojure
(foo
(bar
))
```

Results in the expected:
```clojure
(foo
 (bar
  ))
```

EDIT: I'm using cljfmt from ClojureScript, if that has anything to do with anything.

**Comment by weavejester** [comment]
Yes, your expectation is correct. I'll accept a PR to fix it.

**Comment by PEZ** [comment]
There is hope! 😄 and this is great. It means I can continue to try make Calva Formatter contribute to help with setting a community standard using `cljfmt`.

Not sure about my capacity of providing the PR, I am spreading myself a bit thin, maybe, but this is important. Starting to realize where @bbatsov's rants stem from. Haha. But I'll find a way to get this done.

**Comment by dotemacs** [comment]
> I'm using `cljfmt/reformat-string` with this option map: `{:remove-surrounding-whitespace? false}`
> 
> Formatting:
> 
> ```clojure
> (foo
> (bar
> )
> )
> ```
> 
> I expect:
> 
> ```clojure
> (foo
>  (bar
>   )
>  )
> ```
> 
> But I get:
> 
> ```clojure
> (foo
>  (bar
> )
>  )
> ```

Hi,

not saying that I'll do this, but I just tested this and for me:

```
cljfmt.core> (reformat-string "(foo\n(bar\n)\n)\n")
(foo
 (bar))

cljfmt.core> (reformat-string "(foo
(bar
)
)
")
(foo
 (bar))
```

I don't get the formatting that you describe @PEZ.

This is with `cljfmt` that is currently in `master`.

**Comment by dotemacs** [comment]
I'm blind, didn't see `{:remove-surrounding-whitespace? false}`.

Please ignore me :)

**Comment by PEZ** [comment]
>  not saying that I'll do this

Please say that you will! :smile:
