### ISSUE TITLE
Some ”empty” forms get inconsistent formatting when keeping surrounding whitespace

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#152]
When indenting and keeping surrounding whitespace some forms, like `comment` and `let` get the wrong formatting if they are ”empty” and have newlines. Like this:

```clojure
  (cljfmt/reformat-string "(let []\n)"
                          {:remove-surrounding-whitespace? false
                           :indentation? true}) => "(let []\n     )"
```

I.e. the closing paren is aligned with the first argument of the form. Which is not how let is fomatted otherwise. It should have two space indents for the code below the bindings box.

For empty `comment` forms it is that the closing paren gets one indent when it should have two, like it has when it has contents. I think I have noticed this on other forms too.

For Calva Formatter this is important because it is used while typing and many forms start out empty.

**Comment by PEZ** [comment]
I wonder if this could have been introduced by #143? What do you think, @pfeodrippe ?

**Comment by pfeodrippe** [comment]
I'm going check this today, @PEZ, thanks! 

Let's write a test for this and anything else you and other users can think worth it and that's not covered by the actual tests, do you have more use cases for `clj-fmt` that are not tested?

**Comment by PEZ** [comment]
I suspect there are some uncovered cases with keeping existing whitespace, because I think most often `cljfmt` is used in a way that whitespace is removed. But this is the only case that I have observed a misbehaviour like this, apart from the ones you just fixed. I tried an older version of `cljfmt` and could see that it was not #143 that introduced this issue, btw.

**Comment by lread** [comment]
Hi guys, if we fix this one, I think the current symptoms of #111 will also be addressed. 
Shall I take a stab at it @pfeodrippe? Or are you into it already?
