### ISSUE TITLE
cond clauses formats differently when incomplete than when complete

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#159]
These two should be indented the same (and like the second one):

```clojure
(cond foo
  )

(cond foo
      bar)
```

But they get indented as shown. Here's a repro:

```clojure
(cljfmt/reformat-string "(cond foo\n)\n\n(cond foo\nbar)"
                        {:remove-surrounding-whitespace? false})
=> "(cond foo\n  )\n\n(cond foo\n      bar)"
```

Not sure if this was introduced by #156, but it seems related at least.

**Comment by mseddon** [comment]
https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/core.cljc#L250 disabling this test in #156 definitely fixes this issue,  but of course, reintroduces #156...
