### ISSUE TITLE
Line separator changed from CRLF to LF when formatting text

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#161]
If I feed `(reformat-string) with a text where lines are separated the Windows way, CRLF, it gives me back a text where the lines are separated the Unix way, LF. That is not y design, right? I can attempt fix it in a PR, but need some guidance.

The second of these assertions fail on my machine, a Mac. As the issues list has nothing open on this I am suspecting it is not an issue on Windows machines.

```clojure
(deftest test-keeps-line-separator
  (is (= (reformat-string "foo\nbar") "foo\nbar"))
  (is (= (reformat-string "foo\r\nbar") "foo\r\nbar")))
```

Is this a good way to test this?

**Comment by weavejester** [comment]
You can use `wrap-normalize-newlines` for this, e.g.

```clojure
((wrap-normalize-newlines reformat-string) "foo\r\nbar")
```

**Comment by PEZ** [comment]
Ah, thanks!

That means the behavior I see is expected?

**Comment by weavejester** [comment]
Yes, though I might combine `reformat-string` with `wrap-normalize-newlines`, or possibly move `wrap-normalize-newlines` into `cljfmt.platform` or something like that.

**Comment by PEZ** [comment]
OK. I can't quite figure out how to pass my config map to `reformat-string` this way. Doing:

```clojure
((wrap-normalize-newlines reformat-string) s config)
```
seems to reformat w/o my config. Doing:

```clojure
((wrap-normalize-newlines (partial reformat-string s)) config)
```
Seems to honor some of my config, but not others. (At least I get different results, and fewer of my tests break.)

I guess it's because I am Clojure (and functional) noob that I am missing something obvious with the API.

Anyway, in my usage I know the line separator that should be used, so I get away with:

```clojure
(-> s
    (cljfmt/reformat-string config)
    (clojure.string/replace #"\r?\n" eol))
```

But, I'd love to learn how it could have been done with that wrapper. :smile:

**Comment by weavejester** [comment]
```clojure
((wrap-normalize-newlines #(reformat-string % config)) s)
```
