### ISSUE TITLE
Make fuzzy def rule smarter

### ISSUE THREAD

**Issue by vemv** [weavejester/cljfmt#162]
https://github.com/weavejester/cljfmt/blob/a4bf76174b8c43d18abcedec9072ef42f27cd423/cljfmt/resources/cljfmt/indents/fuzzy.clj

`"^def"` will match things like `default-translation-function` which aren't "defs", ruining indentation.

I propose placing a small blacklist of widely used words starting with `def` which aren't definitions, e.g. `[default defer deflate]`.

They could either be inlined in the existing regex, or expressed as code in core.clj.

Agreed?

Can contribute a PR.

Cheers - Victor

**Comment by weavejester** [comment]
That's not a bad idea. They should be inlined into the regex, if possible.
