### ISSUE TITLE
Qualifed indent specs are not applied in the referred namespace itself

### ISSUE THREAD

**Issue by vemv** [weavejester/cljfmt#166]
Hi there,

I found an issue which is best explained with a suggested failing test (which I ran and indeed fails):

```clojure
    (is (reformats-to?
         ["(ns thing.core"
          ")"
          ""
          "(defthing foo [x]"
          "(+ x 1))"]
         ["(ns thing.core"
          ""
          "(defthing foo [x]"
          "  (+ x 1))"]
         {:indents {'thing.core/defthing [[:inner 0]]}})
        "recognises the current namespace as part of a qualifed indent spec")
```

i.e., if `*ns*` is `thing.core`, then cljfmt should look for an unqualified `defthing` (in addition to the current behavior).

I can give a shot to a fix, but perhaps you have it easy. Let me know

Cheers - Victor

**Comment by weavejester** [comment]
Yes, this seems like a good addition.
