### ISSUE TITLE
Bump rewrite-clj to 0.6.1?

### ISSUE THREAD

**Issue by vemv** [weavejester/cljfmt#170]
Would solve the following `:pedantic?` warn which otherwise I'm not sure I can solve (because both lines begin with `<my-project>`, i.e. I cannot add just `:exclusions`, since that would remove rewrite-clj altogether)

```
<my-project> -> [cljfmt "0.6.4"] -> [rewrite-clj "0.6.0"]
 overrides
<my-project> -> [clj-kondo "2019.05.19-alpha"] -> [rewrite-clj "0.6.1"]
```

WDYT?

Thanks - Victor

**Comment by weavejester** [comment]
You should be able to just include your own rewrite-clj dependency to solve the warning, but I can update.

**Comment by vemv** [comment]
True! Realised a bit late.

> but I can update.

might be desirable
