### ISSUE TITLE
#154 doesn't look fixed

### ISSUE THREAD

**Issue by mynomoto** [weavejester/cljfmt#172]
Hello,

Issue has been closed but it does not look like version ```0.6.4``` fixes the multi-arity defn.
```diff
lein cljfmt check
Retrieving lein-cljfmt/lein-cljfmt/0.6.4/lein-cljfmt-0.6.4.pom from clojars
Retrieving cljfmt/cljfmt/0.6.4/cljfmt-0.6.4.pom from clojars
Retrieving lein-cljfmt/lein-cljfmt/0.6.4/lein-cljfmt-0.6.4.jar from clojars
Retrieving cljfmt/cljfmt/0.6.4/cljfmt-0.6.4.jar from clojars
src/play_with_fmt/core.clj has incorrect formatting
--- a/xxxxxxxxxxxxxxxxxxxxxxxxx/play-with-fmt/src/play_with_fmt/core.clj
+++ b/xxxxxxxxxxxxxxxxxxxxxxxx/play-with-fmt/src/play_with_fmt/core.clj
@@ -21,9 +21,9 @@

 (defn multi-arity
   ([x]
-   body)
+    body)
   ([x y]
-   body))
+    body))

1 file(s) formatted incorrectly
```
My lein cljfmt configuration
```clojure
  :cljfmt {:remove-consecutive-blank-lines? false
           :indents ^:replace {#"^[-*+!?_a-zA-Z]" [[:inner 0]]}}
```

_Originally posted by @kawas44 in https://github.com/weavejester/cljfmt/issues/154#issuecomment-498066248_

I'm having the same problem, following instructions from #154 doesn't format multiarity defn correctly.

**Comment by weavejester** [comment]
I don't understand the problem. You've specified a constant indent of 2 spaces, and your diff shows a constant indent of 2 spaces. Am I missing something here?

**Comment by mynomoto** [comment]
The expression `[x]` that is the first element of the list doesn't match the regular expression and from my understanding it should have being indented with only 1 space. Please let me know if I did understand that wrong. Thanks!

**Comment by weavejester** [comment]
Ah, I see what you mean. Yes, you're correct. I've investigated and I discovered that cljfmt's indentation rules were getting confused around `[x]` and matching the rule against on `(str false)`. The fix was just to add in a missing `symbol?` check to filter out non-symbols from being matched against the indentation rules.
