### ISSUE TITLE
extra lines with assoc

### ISSUE THREAD

**Issue by viebel** [weavejester/cljfmt#173]
The following `assoc` form is badly formatted according to cljfmt. And that seems like an error to be.

```clojure
(assoc context
       :aaa "dsad"
       :bbb "confirm-message"
       :name "aa")
```

```bash
$ clojure -R:dev -m cljfmt.main check /tmp/bb.clj
/tmp/bb.clj has incorrect formatting
--- a/private/tmp/bb.clj
+++ b/private/tmp/bb.clj
@@ -1,4 +1,6 @@
 (assoc context
        :aaa "dsad"
        :bbb "confirm-message"
-       :name "aa")
+       :name
+
+       "aa")
1 file(s) formatted incorrectly
```

**Comment by weavejester** [comment]
Can you give some more information about your setup? I can't reproduce your results.

**Comment by kommen** [comment]
This issue depends on extra newlines at the end of the file.

It reproduces for me with this (note the 2 newlines at the end):
<img width="319" alt="Screenshot 2019-08-07 at 09 46 46" src="https://user-images.githubusercontent.com/258/62604424-58a32d80-b8f8-11e9-8aeb-de1ad6f69573.png">

Removing one of the newlines at the end, the code ends up being formatted correctly.

**Comment by viebel** [comment]
I confirm what @kommen just wrote.

**Comment by anyayunli** [comment]
I also confirmed what @kommen just wrote.

**Comment by or** [comment]
I can reproduce this until version 0.6.2, but https://github.com/weavejester/cljfmt/pull/157, fixed it. I think this issue can be closed.
