### ISSUE TITLE
Allow specification of default paths in project.clj

### ISSUE THREAD

**Issue by samwagg** [weavejester/cljfmt#177]
I have a project where I want to check the format of edn files that aren't in `:source-paths` or `:test-paths`. I don't want developers to have to remember which paths to include as command-line params. I also don't want to define a lein alias, because I want people who are familiar with `cljfmt` to just use it the way they're used to.

If this feature makes sense to you, I'm happy to open a PR. If so, one question is how to specify the default paths. I was leaning toward having a separate, top level `:cljfmt-paths` option over adding an option to `:cljfmt`, because currently it looks like the `:cljfmt` map is just passed through directly to the `check` and `fix` clojure functions, and I think it would be good to maintain that purity.

**Comment by weavejester** [comment]
This seems fine. I'd rather a new key be added to the `:cljfmt` map, perhaps just `:paths`.

**Comment by weavejester** [comment]
Fixed by #180.
