### ISSUE TITLE
Ignore shebang

### ISSUE THREAD

**Issue by pfeodrippe** [weavejester/cljfmt#178]
Hi,It's more a question, I am making a script with babashka and trying to use cljfmt, there is any way to simple ignore some lines (example, the shebang at start of the file)?

**Comment by lread** [comment]
A new release of rewrite-clj that specifically understand `#!` is coming very soon.
I don't know if it is documented but `#!` is equivalent to `;`.

```Clojure
#! I am a comment
; So am I!
```

I'll come back and update cljfmt with the new version of rewrite-clj when it is released.

**Comment by pfeodrippe** [comment]
Thanks!!
