### ISSUE TITLE
cljfmt support lein version? 

### ISSUE THREAD

**Issue by yangwansu** [weavejester/cljfmt#18]
my lein version is 2.2.0.

so next exception occured.

java.lang.RuntimeException: No such var: main/warn, compiling:(leiningen/cljfmt.clj:61:14)

I has resolved by version 2.5.0.

thank you.

**Comment by weavejester** [comment]
Leiningen 2.2.0 is almost two years out of date. I've only tested cljfmt with modern versions of Leiningen, so you may run into problems using older versions.
