### ISSUE TITLE
Can't use all indent configuration options via tools.deps

### ISSUE THREAD

**Issue by mynomoto** [weavejester/cljfmt#190]
First, thanks for supporting tools.deps as an option to run cljfmt.

I was trying to migrate cljfmt from using the lein plugin to tools.deps on one project but since the indents file is parsed as edn it doesn't support regexes.
```
[Error while parsing option "--indents indentation.edn": java.lang.RuntimeException: No dispatch macro for: "]
```
Would a change to allow regexes be welcome?

**Comment by hoxu** [comment]
I guess it's not possible to configure this example using edn currently:

    {:indents ^:replace {#".*" [[:inner 0]]}

**Comment by mynomoto** [comment]
> I guess it's not possible to configure this example using edn currently:
> 
> ```
> {:indents ^:replace {#".*" [[:inner 0]]}
> ```

Yeah, sorry for not providing a example when I opened the issue.

**Comment by hoxu** [comment]
@weavejester @mynomoto: any workarounds or ideas how to fix this?

**Comment by mynomoto** [comment]
So far I'm still using lein to avoid the issue. I think you can build your own function to read a clj file, I just wanted feature parity out of the box.

**Comment by weavejester** [comment]
Sorry for the late response. Perhaps the best solution to this would be to allow `--indents` to reference a `.clj` file as well as a `.edn` file, and use the appropriate `read-string` depending on the file extension.

**Comment by mynomoto** [comment]
> Sorry for the late response. Perhaps the best solution to this would be to allow --indents to reference a .clj file as well as a .edn file, and use the appropriate read-string depending on the file extension.

This would be a nice solution. Would a pr be welcome?

**Comment by weavejester** [comment]
> This would be a nice solution. Would a pr be welcome?

Yep.

**Comment by lread** [comment]
@weavejester can this be closed?  Looks like a solution was merged?

**Comment by weavejester** [comment]
Yep, this looks fixed.
