### ISSUE TITLE
Two lines between top level definitions

### ISSUE THREAD

**Issue by achikin** [weavejester/cljfmt#191]
We use codestyle with two lines between top level definitions like this
```
(defn a [])

(defn b [])
```
Can I set this up in cljfmt?

**Comment by weavejester** [comment]
cljfmt has `:remove-consecutive-blank-lines?` as an option, but doesn't currently have an option to mandate a blank line between top level forms. PRs are welcome.

**Comment by weavejester** [comment]
cljfmt has `:remove-consecutive-blank-lines?` as an option, but doesn't currently have an option to mandate a blank line between top level forms. PRs are welcome.
