### ISSUE TITLE
Need a blank project.clj to use tools.deps version?

### ISSUE THREAD

**Issue by rgm** [weavejester/cljfmt#192]
Apologies if this is me doing something not quite right in my projects, but, well:

Steps:  
1. Add `cljfmt {:mvn/version "0.6.7"}` to `deps.edn`
2. Run `clojure -m cljfmt.main check` in a project that has a `deps.edn` file but no `project.clj`

Expected:  
The linter should run.

Actual:  
shell reports `No such file: project.clj`

Notes:
Doing `touch project.clj` to get a completely blank Lein project file and then re-running gives me `All source files formatted correctly`

**Comment by weavejester** [comment]
This looks like a bug. PRs to fix it are welcome.

**Comment by rgm** [comment]
OK, I'll dig in 👍.
