### ISSUE TITLE
Could we have a new release?

### ISSUE THREAD

**Issue by djblue** [weavejester/cljfmt#198]
The latest commit on master allows for use of cljfmt in deps.edn based projects. Thanks!

**Comment by weavejester** [comment]
Release 0.6.8.

**Comment by jngbng** [comment]
Please release for lein based project, too. Thanks!
Currently, 0.6.7 is the latest: https://repo.clojars.org/lein-cljfmt/lein-cljfmt/maven-metadata.xml

**Comment by weavejester** [comment]
That's odd... it must not have uploaded. It should be up now.
