### ISSUE TITLE
Default formatting not aligning let blocks statements vertically

### ISSUE THREAD

**Issue by cksharma11** [weavejester/cljfmt#201]
I want to format my code something like below

from this
```
(let [username "username"
      pwd "pwd"
      email "email"])
```
to this
```
(let [username "username"
      pwd      "pwd"
      email    "email"])
```

But when I'm doing `lein cljfmt check` it's not giving any error for the same.

**Comment by weavejester** [comment]
cljfmt does not yet support this feature. PRs are welcome.

**Comment by weavejester** [comment]
Closing because this is a duplicate of #36.
