### ISSUE TITLE
Nested keyword issue

### ISSUE THREAD

**Issue by narkisr** [weavejester/cljfmt#204]
Running lein cljfmt check on the following function:

```clojure
 (extend-type Hosts
    Devices
    (usb
      ([this]
       [this (run-hosts this run-query  ['[:find ?v :where [_ :usb-devices/connected-devices/name ?v]]] [5 :second])])
      ([this _]
       (usb this))))
```
Results with:

```bash
Failed to format file: src/re_mote/zero/devices.clj
clojure.lang.ExceptionInfo: Invalid token: :usb-devices/connected-devices/name
{:type :reader-exception, :line 17, :column 96}
 at clojure.tools.reader.reader_types$reader_error.doInvoke (reader_types.clj:336)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.tools.reader.edn$read_keyword.invoke (edn.clj:272)
    clojure.tools.reader.edn$read.invoke (edn.clj:372)
    clojure.tools.reader.edn$read.invoke (edn.clj:361)
    clojure.tools.reader.edn$read.invoke (edn.clj:358)
    rewrite_clj.parser.keyword$parse_keyword.invokeStatic (keyword.clj:18)
    rewrite_clj.parser.keyword$parse_keyword.invoke (keyword.clj:8)
    rewrite_clj.parser.core$eval2439$fn__2440.invoke (core.clj:96)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    rewrite_clj.reader$read_with_meta.invokeStatic (reader.clj:132)
    rewrite_clj.reader$read_with_meta.invoke (reader.clj:128)
    rewrite_clj.parser.core$parse_next.invokeStatic (core.clj:35)
    rewrite_clj.parser.core$parse_next.invoke (core.clj:33)
    rewrite_clj.parser.core$parse_delim$fn__2407.invoke (core.clj:43)
```

This is valid Clojure syntax :)

**Comment by lread** [comment]
Hi @narkisr, 

From [Clojure docs](https://clojure.org/reference/reader#_reader_forms):
> '/' has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. my-namespace/foo. '/' by itself names the division function.

So your keyword is not technically legal in Clojure.  Does [re-ops/re-core](https://github.com/re-ops/re-core) encourage or force this illegal syntax?

**Comment by narkisr** [comment]
It is legal in the sense that this code is running and I'm able to access map values using this key, these keys describe the flattening of nest maps into a single level map.

BTW I'm not the first one who played with this idea https://clojuredocs.org/clojure.core/keyword#example-5c4c9096e4b0ca44402ef63d

**Comment by narkisr** [comment]
Any case ill close this issue since I have a workaround I can use, thank for the help
