### ISSUE TITLE
Support form feed/page-break/Ctrl-L

### ISSUE THREAD

**Issue by MicahElliott** [weavejester/cljfmt#207]
Then we could do things like what's shown in the screenshot here: https://github.com/purcell/page-break-lines

**Comment by lread** [comment]
What is cljfmt doing now @MicahElliott? 
Is it stripping the FF character?

**Comment by lread** [comment]
Without more detail I don't really understand this request, can we close @weavejester?

**Comment by MicahElliott** [comment]
Oops. Yes, the page-break is rejected as being an extra (triple) newline (IIRC).

**Comment by lread** [comment]
Thanks @MicahElliott, so you'd like FF to simply be retained as-is rather than be interpreted as a newline? (I've not done any testing, so I'm just guessing at current behaviour).

**Comment by MicahElliott** [comment]
Correcto @lread . Thanks!!

So `\n\n\l\n` is accepted, but `\n\n\n` is still rejected.

**Comment by lread** [comment]
@MicahElliott I'm sorry, I am feeling a bit dense here.

Can you clearly explain:
1. exactly what is happening now
2. exactly what would you like to happen instead and why

**Comment by MicahElliott** [comment]
Input file:
```
(ns foo)

^L

(defn bar ...)

```


```
% lein cljfmt check .../foo.clj
...
test/.../foo.clj has incorrect formatting
--- a/foo.clj
+++ b/foo.clj
@@ -9,8 +9,6 @@
))
 
-

-

```

I feel that this should be not flagged since there's really not a triple-newline present, though cljfmt thinks there is, because it's treating page-break as nothing (removing/ignoring it).

**Comment by lread** [comment]
Thanks @MicahElliott, that helps. And you'd like to retain the FF because it is visually relevant to some tooling you are using.

**Comment by MicahElliott** [comment]
Yes, basically exactly what's shown in this screenshot: https://github.com/purcell/page-break-lines#screenshot

The only workaround presently is to break sections with something like:
```
;;; -----------------
;;; SOME SECTION
```

I don't know how many dashes are there because I just held down the button (like many do), and everyone does this differently and that's is a shame.

**Comment by MicahElliott** [comment]
Hi @lread! Do you think the right approach to this would be adding a `formfeed?` predicate function to `rewrite-clj.reader`? Then cljfmt would be able to be tweaked to treat it specially as non-whitespace?

**Comment by lread** [comment]
Hi @MicahElliott, it might go deeper than that.
The rewrite-clj reader uses [clojure.tools.reader](https://github.com/clojure/tools.reader). 
We'd have to also study how this reader interprets formfeed and possibly tweak its behavior.

And... probably best to check with @weavejester before spending any more time on this. 
If he's not into supporting cljfmt passing through formfeeds (which I think would still be considered whitespace) then it is probably not worth pursuing this further.

**Comment by MicahElliott** [comment]
Yeah, ok, makes sense. It is an odd case of "kinda whitespace sometimes". There are cool things that unix tools/editors have been able to do with FFs, but this case is not all that important anyway. Thanks for the consideration though! And for all the nice work on this tooling!

**Comment by lread** [comment]
@MicahElliott if you find enough people that are into this feature and @weavejester doesn't object to it, then it might still be a possibility.

**Comment by weavejester** [comment]
I don't mind as long as someone else does the work and it doesn't affect anything else.

**Comment by MicahElliott** [comment]
A workaround to enable both page-break-lines to display these nicely, and let an editor (eg, Emacs' `forward-page`) jump around the page-breaks, is to put a trailing semicolon after the page-break:
```
  ... end of some code

^L;
;;; My Heading

(defn ...
```

![image](https://user-images.githubusercontent.com/159047/159379421-65009497-e3e3-4867-9999-de54879623da.png)
