### ISSUE TITLE
lein cljfmt does not supports cli arguments

### ISSUE THREAD

**Issue by mracos** [weavejester/cljfmt#208]
Looks like it's because the cljfmt `lein-plugin` [interprets every argument](https://github.com/weavejester/cljfmt/blob/master/lein-cljfmt/src/leiningen/cljfmt.clj#L23) after the command as a path to check

**Comment by weavejester** [comment]
Yes, because typically in Leiningen you use profiles and `update-in` instead to affect configuration options.

**Comment by mracos** [comment]
Thanks for the quick response 💙 
I see I see, you would not happen to have an example up on your sleeve would ya? 👀

**Comment by weavejester** [comment]
An example of Leiningen profiles, or update-in?

**Comment by mracos** [comment]
Sorry for the lack of context, tried to add more info in the comment above.
An example on how could I use `update-in` to use a custom indents file, if you could please!

**Comment by mracos** [comment]
The only that I got working was by defining a `cljfmt` alias to mimic the lein plugin call but using my custom indents file. e.g.

```clojure
:aliases {"cljfmt" ["run" "-m" "cljfmt.main" "--indents" ".custom-indents.edn"]}
```

**Comment by weavejester** [comment]
Ah, so with context, I think you want something like:

```clojure
:cljfmt {:indents ~(-> "./.custom-indents.edn" slurp read-string)}
```

The `~` in a Leiningen project file will trigger an evaluation.

**Comment by mracos** [comment]
TIL about the `~`. Well then, thank you so much for your help! 💙 
Sorry for opening an issue that's not really an issue 😄
