### ISSUE TITLE
strange lint suggestion?

### ISSUE THREAD

**Issue by NickeZ** [weavejester/cljfmt#209]
Hello,

I've got my minimal reproducible example to:

```
(a)


; b
(c)
```

here it suggests

```
src/test.clj has incorrect formatting
--- a/tmp/cljfmttest/src/test.clj
+++ b/tmp/cljfmttest/src/test.clj
@@ -2,4 +2,6 @@


 ; b
+
+
 (c)
1 file(s) formatted incorrectly
```

which seems wrong to me. Is this the intended behavior? I would like to have my comment tightly coupled to the line after.

**Comment by lread** [comment]
Yeah that seems wrong @NickeZ.

Like you I would expect
```Clojure
a




; b
c
```

To reformat to:
```Clojure
a

;b
c
```

I can take a look at this after #213 is merged.

**Comment by lread** [comment]
@weavejester, I am thinking that it would be consistent to collapse consecutive blank lines between comments as well.

```Clojure
a


;b


;c


d
```

Would reformat to:
```Clojure
a

;b

;c

d
```

Would this be desirable behaviour?

**Comment by lread** [comment]
@weavejester, while I'm looking at collapsing blank lines, I see that comma treatment might be a bit odd?

Do we consider a comma to be a blank line?  This, for example, does not collapse:
```Clojure
a

,

b
```
But... if we introduce enough blank lines before (and/or after) the comma (or commas):
```Clojure
a


,

b
```

then we do get a collapse (including the removal of the commas):

```Clojure
a

b
```

**Comment by weavejester** [comment]
Collapsing multiple blank lines between comments seems fine. We could also probably treat lines with only commas as blank lines, or add an option to fix commas that are at the end or beginning of lines.

**Comment by lread** [comment]
Thanks @weavejester, I shall make it so.

> We could also probably treat lines with only commas as blank lines

I'll start with this.  We can add a fix option at some later date if folks want/need it.
