### ISSUE TITLE
incorrectly inserts space in valid var names that have a colon in them.

### ISSUE THREAD

**Issue by MarcoPolo** [weavejester/cljfmt#21]
e.g.
```clojure 
-(defn foo:bar
+(defn foo :bar
   "I don't do a whole lot."
   [x]
   (println x "Hello, World!"))
```

It should not insert a space.

**Comment by weavejester** [comment]
What makes you say this is a valid symbol name? The reader docs say it isn't, and there aren't any functions or macros in the Clojure core or contrib libraries to suggest otherwise.

**Comment by MarcoPolo** [comment]
Looking at http://clojure.org/reader

> Symbols begin with a non-numeric character and can contain alphanumeric characters and \*, +, !, -, _, and ? (other characters will be allowed eventually, but not all macro characters have been determined). '/' has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. my-namespace/foo. '/' by itself names the division function. '.' has special meaning - it can be used one or more times in the middle of a symbol to designate a fully-qualified class name, e.g. java.util.BitSet, or in namespace names. Symbols beginning or ending with '.' are reserved by Clojure. Symbols containing / or . are said to be 'qualified'. Symbols beginning or ending with ':' are reserved by Clojure. **A symbol can contain one or more non-repeating ':'s.**

**Comment by weavejester** [comment]
I stand corrected!

I didn't notice that the end sentence explicitly allows `:` in symbol names, because the first sentence doesn't include them in the list of allowed characters.

I'll bring this up with rewrite-clj. I wish Clojure had less ambiguous reader documentation.
