### ISSUE TITLE
Workaround for clojure.stacktrace no longer needed for native-image

### ISSUE THREAD

**Issue by borkdude** [weavejester/cljfmt#210]
This was fixed in Clojure 1.10.2.

https://github.com/weavejester/cljfmt/blob/e75c430dab52c766828007a1ed32089419370134/cljfmt/src/cljfmt/impl/stacktrace.clj#L17

**Comment by lread** [comment]
@bsless, this was certainly needed when you added it, but that is no longer the case.  
Shall we remove?
Does any other native-image support need to be updated?

**Comment by bsless** [comment]
I'll review my changes and see what can be removed
