### ISSUE TITLE
Consider upgrading to rewrite-clj v1

### ISSUE THREAD

**Issue by lread** [weavejester/cljfmt#211]
I've recently released [rewrite-clj v1](https://github.com/clj-commons/rewrite-clj/blob/main/CHANGELOG.adoc#rewrite-clj-v1). 

Even though it is labelled, alpha, it is feeling solid.
I am already [successfully running cljfmt's tests against rewrite-clj v1](https://github.com/clj-commons/rewrite-clj/blob/main/doc/02-developer-guide.adoc#libs-test).

Upgrading to rewrite-clj v1 should fix many cljfmt issues that were previously waiting on fixes in rewrite-clj v0 and rewrite-cljs.

Potentially problematic? (lemme know!):
- rewrite-clj v1 min Clojure version is 1.9
- rewrite-clj v1 ClojureScript performance could be less than that of rewrite-cljs. I dropped rewrite-cljs specific tunings in favour of a single code base. I do plan to address any real performance issues.

I am happy to:
- Compare cljfmt test suite execution time with rewrite-cljs vs rewrite-clj v1 to get some idea of potential degradations.
- Create a rewrite-clj v1 upgrade PR which will include a review current open cljfmt issues, and when appropriate, the addition of tests to verify that they are fixed by rewrite-clj v1

**Comment by lread** [comment]
For ClojureScript testing, here is what I have done so far.

From my development computer:

- Late 2013 iMac 
- 3.5 GHz Quad-Core Intel Core i7 
- 32 GB or RAM

Created a primitive benchmark in `bench.cljs`
```Clojure
(ns bench
  (:require [cljfmt.core-test]
            [clojure.test :as t]))

(defn bench [desc iterations]
  (println (str "=" desc "=>") iterations "iterations")
  (simple-benchmark [] (t/run-all-tests #"cljfmt.core-test") iterations))

(defn -main []
  (bench "warm up" 3) 
  (bench "run" 100))

(set! *main-cli-fn* -main)
```
Compiled and ran for `node` with no optimizations against rewrite-cljs then rewrite-clj v1:
- rewrite-cljs 
  - 100 runs, 70967 msecs
- rewrite-clj v1
  - 100 runs, 85576 msecs
  
Which means that the cljfmt test run is ~20% slower with rewrite-clj v1 under the above tests.
I realize this is not terribly thorough or conclusive, but it does give us some inkling of perf impact.

My feeling is that, if the perf impact above is representative, it is a small price to pay for the benefits that rewrite-clj v1 will bring to cljfmt ClojureScript users.  Other opinions are most welcome.

[Saved work and results](https://github.com/lread/cljfmt/commit/affdd0d74f31b4f5fa2a79189516d3ef3504e974) to [a branch on my cljfmt fork](https://github.com/lread/cljfmt/tree/lread-rewrite-cljs-bench)

Feedback welcome and appreciated.
Also happy to do more testing.

**Comment by vemv** [comment]
Given that cljfmt offers both a native image, and a JVM API that can bypass Lein and be safely invoked in parallel, perhaps performant-conscious cljfmt is fast enough that a 20% slowdown is not quite impactful.

It is also predictable that rewrite-clj will be further optimized over time :)

**Comment by weavejester** [comment]
> rewrite-clj v1 min Clojure version is 1.9
> rewrite-clj v1 ClojureScript performance could be less than that of rewrite-cljs. I dropped rewrite-cljs specific tunings in favour of a single code base. I do plan to address any real performance issues.

I don't see those as blockers. We can update to rewrite-clj v1 and see what happens.

**Comment by ericdallo** [comment]
It'd be nice to link cljfmt issues that would be fixed with this bump :)

**Comment by lread** [comment]
> It'd be nice to link cljfmt issues that would be fixed with this bump :)

@ericdallo  #106 and #171 will be fixed by switching to rewrite-clj v1.
I will review for other issues that might be fixed as part of the PR.

For me, the perhaps more exciting thing is that this will bring feature parity for usage of rewrite-clj from Clojure and ClojureScript making future changes easier.  For example, [I should be able to revert work-arounds like this](https://github.com/weavejester/cljfmt/commit/5240a1ec87832fb8ebc754693dcf628e877fe13b).
