### ISSUE TITLE
#202 breaks native-image build

### ISSUE THREAD

**Issue by bsless** [weavejester/cljfmt#217]
Following the request in #210 I came to review my recent changes and found that native image building is broken.
Analysis:
Checked out commit `7571de0`, built a native-image with `lein do clean, native-image`, native image built successfully
Checked out commit `98a7c53`, built a native-image with `lein do clean, native-image`, native image build failed
Possible causes:
`read-string` calls unsupported method `java.lang.ClassLoader.defineClass(String, byte[], int, int)`

@borkdude what do you use in babashka for reading strings? From looking at the code base I see only `edn/read-string` is used. It is sufficient for this use case?

**Comment by borkdude** [comment]
@bsless Where does cljfmt use read-string and why?

**Comment by bsless** [comment]
@borkdude here:
https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/main.clj#L146
introduced in #202

**Comment by borkdude** [comment]
@bsless I'm not sure if Clojure's `read-string` works in native-image, but worth a try by enabing `--report-unsupported-elements-at-runtime`. In babashka code is read by a custom reader that is in turn based on tools.reader.edn.

**Comment by bsless** [comment]
@borkdude looks like the build works with `--report-unsupported-elements-at-runtime`. I checked binary against several projects, both check and fix commands work.
Can you think of a case which would break the reader in native image?

**Comment by borkdude** [comment]
@bsless `read-string` might use the compiler when reading `#=(+ 1 2 3)`, maybe that's the only case? What kinds of things are read on that command line invocation?

**Comment by bsless** [comment]
@borkdude `read-string` is used on the `slurp`ed contents of a `.clj` file. I tried engineering a case which even defines an anonymous function, didn't manage to break anything.
```clojure
(defn- cli-file-reader [filepath]
  (let [contents (slurp filepath)]
    (if (= (filename-ext filepath) "clj")
      (read-string contents)
      (edn/read-string contents))))
```

**Comment by borkdude** [comment]
@bsless "defining" as in reading the s-expression, or actually creating one? (I suspect the first). How about `#=(+ 1 2 3)`? Not that that should be supported, but just fun to check what happens.
