### ISSUE TITLE
Errors using current (dd51b31) master from a shadow-cljs build

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#225]
Hello,

When I call `cljfmt-core/reformat-string` I get this:

```
npx shadow-cljs cljs-repl :calva-lib
shadow-cljs - config: /Users/pez/Projects/calva/shadow-cljs.edn
shadow-cljs - connected to server
cljs.user=> (in-ns 'calva.fmt.formatter)
nil
calva.fmt.formatter=> (cljfmt.core/reformat-string "foo")

Execution error (TypeError) at (<cljs repl>:1).
Cannot read property 'cljs$core$IFn$_invoke$arity$1' of undefined
nil
calva.fmt.formatter=> cljfmt.core/default-line-separator
"\n"
calva.fmt.formatter=> 
```

Is it supposed to work from `master` right now?

Possibly related to #224

**Comment by weavejester** [comment]
All the tests, both Clojure and ClojureScript, are working on master right now. If you can reproduce this error as a test, we can see about fixing it.

**Comment by PEZ** [comment]
Indeed. The tests passes when I try it too. And they exercise `reformat-string`, so there must be something else going on. I'll see if I can reproduce it more minimally. I mainly wanted to check that it is supposed to work.

**Comment by PEZ** [comment]
It turns out this was a dependency conflict with `zprint`, which of course also uses `rewrite-clj`. Sorry for the noise!
