### ISSUE TITLE
cljfmt fix does not work without project.clj

### ISSUE THREAD

**Issue by ludbek** [weavejester/cljfmt#228]
It seems `cljfmt fix` does not work without `project.cj`.
When I ran `clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.6.4"}}}'  -m cljfmt.main fix` I got following error

```
clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.6.4"}}}' \
		-m cljfmt.main fix
WARNING: When invoking clojure.main, use -M
No such file: project.clj
```

**Comment by seancorfield** [comment]
The README has an old version for the CLI example (0.6.4) instead of the more recent version (0.7.0). The CLI example works as expected if you use 0.7.0 instead of 0.6.4.

**Comment by ludbek** [comment]
Will create a pull request.
