### ISSUE TITLE
Any interest in a clj-kondo config for cljfmt developers?

### ISSUE THREAD

**Issue by lread** [weavejester/cljfmt#232]
Hi @weavejester, I don't know if you use the [clj-kondo](https://github.com/clj-kondo/clj-kondo) linter.
I do and find it quite helpful.
I include it in my build processes and fail builds that have lint errors.

If you are interested, I am happy to do the work.

**Comment by weavejester** [comment]
I had a quick check over it, and it looks like a very useful tool to be used manually, but in the case of cljfmt in particular, it has too many false positives to be included in the build chain.

**Comment by lread** [comment]
Thanks for taking a peek @weavejester. 

Clj-kondo is highly configurable, so we could configure it to enforce whatever opinions are important to you.

Please ignore the remainder of this comment if you have already made up your mind and decided clj-kondo is not a good fit for clfjmt. Personally, I find the benefit of clj-kondo outweighs the cost of maintaining its config, but that's just me and might not be you.

Here's a sample clj-kondo usage:

Initial setup (from cljfmt root dir):

```
cd cljfmt
mkdir .clj-kondo
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs
```

And a run:
```
> clj-kondo --lint src test
src/cljfmt/core.cljc:18:8: warning: Unused private var cljfmt.core/find-all
src/cljfmt/core.cljc:74:48: warning: #'rewrite-clj.zip/append-space is deprecated since 0.5.0
src/cljfmt/core.cljc:207:8: warning: Unused private var cljfmt.core/top-level-form
src/cljfmt/core.cljc:227:3: warning: Missing else branch.
src/cljfmt/core.cljc:233:3: warning: Missing else branch.
src/cljfmt/core.cljc:262:5: warning: Missing else branch.
src/cljfmt/core.cljc:269:21: warning: Missing else branch.
src/cljfmt/core.cljc:282:3: warning: Missing else branch.
src/cljfmt/core.cljc:296:8: warning: unused binding sym
src/cljfmt/core.cljc:296:12: warning: unused binding alias-map
src/cljfmt/core.cljc:296:30: warning: unused binding args
src/cljfmt/diff.clj:2:31: warning: Unused import Delta$TYPE
src/cljfmt/main.clj:202:8: warning: Unused private var cljfmt.main/command-name
test/cljfmt/core_test.cljc:7:14: warning: namespace cljfmt.test-util.common is required but never used
test/cljfmt/core_test.cljc:13:10: error: Unresolved symbol: reformats-to?
test/cljfmt/test_runner.cljs:4:14: warning: namespace cljfmt.core-test is required but never used
test/cljfmt/test_util/cljs.cljc:2:14: warning: namespace cljs.test is required but never used
test/cljfmt/test_util/cljs.cljc:3:14: warning: namespace cljfmt.test-util.common is required but never used
linting took 217ms, errors: 1, warnings: 17
```

And let's go over some of the warnings:


```
src/cljfmt/core.cljc:18:8: warning: Unused private var cljfmt.core/find-all
src/cljfmt/core.cljc:207:8: warning: Unused private var cljfmt.core/top-level-form
```
Clj-kondo [currently does not distinguish warnings for clj vs cljs](https://github.com/clj-kondo/clj-kondo/issues/1196). These warnings effectively mean these vars are not used for the cljs platform.  They probably should be wrapped with a reader conditional.

```
src/cljfmt/core.cljc:74:48: warning: #'rewrite-clj.zip/append-space is deprecated since 0.5.0
```
Interesting, we could switch away from using a deprecated fn.

```
src/cljfmt/core.cljc:227:3: warning: Missing else branch.
```
This is a default opinion of clj-kondo. Its opinion is that `when` should be used instead of `if` when there is no else branch. When we use `when` the reader of the code knows there is no else and does not have to look for it or think about it.

```
src/cljfmt/core.cljc:296:12: warning: unused binding alias-map
```
Another default opinion of clj-kondo.  It suggests unused bindings should be prefixed with an `_`.
I personally agree with this opinion in general, but not for this case which is a defmulti.  
Until [clj-kondo addresses this issue](https://github.com/clj-kondo/clj-kondo/issues/1188), I'd suppress the warning for this case.

```
src/cljfmt/diff.clj:2:31: warning: Unused import Delta$TYPE
src/cljfmt/main.clj:202:8: warning: Unused private var cljfmt.main/command-name
```
These seem to be legitimately unused.  Probably can delete.

```
test/cljfmt/core_test.cljc:7:14: warning: namespace cljfmt.test-util.common is required but never used
test/cljfmt/core_test.cljc:13:10: error: Unresolved symbol: reformats-to?
test/cljfmt/test_runner.cljs:4:14: warning: namespace cljfmt.core-test is required but never used
test/cljfmt/test_util/cljs.cljc:2:14: warning: namespace cljs.test is required but never used
test/cljfmt/test_util/cljs.cljc:3:14: warning: namespace cljfmt.test-util.common is required but never used
```
These have to do with the custom assert-expr I wrote a while back.  
We'd have to tell clj-kondo about reformats-to? and I expect the code could use some cleanup.  
If cleanup is uninteresting, we could tell clj-kondo to ignore these issues.

**Comment by weavejester** [comment]
Yep, I read through the warnings. It was the false positives around the tests I was referring to. Warnings for unused namespaces are useful, but how would clj-kondo disguish between genuine unuse and libraries that scan the vars in a namespace?

**Comment by lread** [comment]
Hey, thanks for continuing the discussion!

> Yep, I read through the warnings. It was the false positives around the tests I was referring to.

I really struggled to get the `reformats-to?` `assert-expr` working for both clj and cljs.
I remember settling on doing odd things like including unused nses.  
It felt sloppy but I did not know what else to do at the time (you were asking questions but kindly let it go).
I'll take a stab at cleanup and see if I can get rid of the weirdnesses.

Regardless of cleanup I'd have to tell clj-kondo about `reformats-to?`;  I'd likely start by telling clj-kondo to just ignore it.

> but how would clj-kondo disguish between genuine unuse and libraries that scan the vars in a namespace?

Clj-kondo will ignore any ns that is required without an alias. 

But it is a static source code analyzer.
So any load time modification/creation of vars (if that's what you mean?) won't be recognized out of the box.
That said, there is support for custom hooks that can fill the gaps for these cases.  
At one point I had a custom version of potemkin import-vars within rewrite-clj and wrote a clj-kondo hook to support linting of vars imported to nses at load time. 
Clj-kondo includes internal hooks to understand the official potemkin import-vars.

**Comment by lread** [comment]
A revisit of the tests warnings:

```
test/cljfmt/core_test.cljc:7:14: warning: namespace cljfmt.test-util.common is required but never used
test/cljfmt/test_runner.cljs:4:14: warning: namespace cljfmt.core-test is required but never used
```
Can be silenced by removing the ns alias on the requires.  We still need the namespace loaded but have no need for an alias.

```
test/cljfmt/core_test.cljc:13:10: error: Unresolved symbol: reformats-to?
```
We'd silence this one, at least initially, by adding a clj-kondo linter config `{linters {:unresolved-symbol {:exclude [reformats-to?]}}}`

```
test/cljfmt/test_util/cljs.cljc:2:14: warning: namespace cljs.test is required but never used
test/cljfmt/test_util/cljs.cljc:3:14: warning: namespace cljfmt.test-util.common is required but never used
```
These two would go away if we renamed the .cljc to a .clj file (there is no need for this to be a .cljc file).
Clj-kondo is noticing they are unused for the cljs platform.

@weavejester, I kinda guessed you'd be excited about clj-kondo, but if this discussion is currently more of burden than something of interest, I know you are a busy person, please do close.

Another option is to include a clj-kondo config but not integrate it in your CI build pipeline.

**Comment by weavejester** [comment]
I think clj-kondo is certainly useful, and I'd like to address the issues it's brought up, particularly around unused functions or imports. But in terms of adding it to the build process, I'm leery on whether it's more trouble than it's worth. Is it worth addressing every false positive, or is it better to manually run it once a year to "spring clean" the codebase?

**Comment by lread** [comment]
Definitely a personal preference. 
As you might have guessed, I am sold on clj-kondo. I have it active in my editor, include a config in all my projects and fail my builds on any warnings.  I don't spend a lot of time fiddling with my clj-kondo configs.

Different things are important to different people. 
I know from experience that commit messages and the quality of contributed code are important to you.
But maybe you don't want clj-kondo involved for every push. 
That's fine.

Would starting with a minimal clj-kondo config without any build/CI stuff be of interest?
I think contributors with clj-kondo active in their editors would appreciate it.

**Comment by weavejester** [comment]
> Would starting with a minimal clj-kondo config without any build/CI stuff be of interest?

That should be fine. What would be configured?

**Comment by lread** [comment]
You can think of it as an experiment that you can turf if it becomes annoying.

To be revisited on PR but here's the `cljfmt/cljfmt/.clj-kondo/config.edn` I am using while working on cljfmt in dev now:

```Clojure
{:config-paths ^:replace ["rewrite-clj/rewrite-clj"]
 :linters {:missing-else-branch {:level :off}
           :unresolved-symbol {:exclude [reformats-to?]}
           :unused-namespace {:exclude [clojure.test cljs.test cljfmt.test-util.common]}}}
```

The `^:replace` says ignore any user default clj-kondo configs.
`rewrite-clj\rewrite-clj` is an export config from rewrite-clj to educate clj-kondo about linting its thread macros.  Its export config will also be included under the `.clj-kondo` dir (not much to it).
I'm making an assumption that you are ok with `if`s that do not have else branches (lemme know if you prefer these to be `when`s).
The `unused-namespace` stuff will not be needed after we make changes I described above.

I'm also using an inline config in `cljfmt.core` (which you may or may not like):
```
(defmulti ^:private indenter-fn
  #_{:clj-kondo/ignore [:unused-binding]}
  (fn [sym alias-map [type & args]] type))
```
This depends if you dislike unused bindings in general. If you have no preference, we could move this to `config.edn` as a global preference.
