### ISSUE TITLE
Unexpected indentation for `condp` (and friends)

### ISSUE THREAD

**Issue by finalfantasia** [weavejester/cljfmt#238]
Given the following forms:
```clojure
;; A
(condp :pred
       :expr
  :test-1 :result-1
  :test-2 :result-2
  :default)

;; B
(condp :pred
  :expr
  :test-1 :result-1
  :test-2 :result-2
  :default)

;; C
(condp
 :pred
 :expr
  :test-1 :result-1
  :test-2 :result-2
  :default)

;; D
(condp
  :pred
  :expr
  :test-1 :result-1
  :test-2 :result-2
  :default)
```
cljfmt 0.8.0 gives me the following check report:
```diff
@@ -7,7 +7,7 @@
 
 ;; B
 (condp :pred
-  :expr
+       :expr
   :test-1 :result-1
   :test-2 :result-2
   :default)
@@ -22,8 +22,8 @@
 
 ;; D
 (condp
-  :pred
-  :expr
+ :pred
+ :expr
   :test-1 :result-1
   :test-2 :result-2
   :default)
```
which is unexpected.

According to [the default indentation rule for `condp`](https://github.com/weavejester/cljfmt/blob/master/cljfmt/resources/cljfmt/indents/clojure.clj#L11) and the following similar example in README.md:
> No arguments on the same line as foo does not break the threshold of 0, so 2 space inner indentation is applied:
```clojure
(foo                               (foo
bar            == formats to =>      bar
baz                                  baz
bang)                                bang)
```

In form A, `:expr` should have been considered **incorrectly** indented and thus cljfmt should have indicated so in the report. This is because the count of form arguments on the same line as the form symbol (1) does not break the threshold (2) so `:expr` should have had 2-space inner indentation.

In form B, `:expr` should have been considered **correctly** indented for the same reason given above and thus cljfmt should have not reported it as having incorrect indentation.

In form C, both `:pred` and `:expr` should have been considered **incorrectly** indented (with **1-space** indentation as opposed to **2-space** indentation) for the same reason and cljfmt should have indicated so in the report.

In form D, both `:pred` and `:expr` should have been considered correctly indented (with **2-space** indentation) for the same reason and thus cljfmt should have not reported them as having incorrect indentation and suggest that they should have been indented with **1 space**, which leads to a strangely indented form that throws Parinfer off in certain cases.

**Comment by weavejester** [comment]
The default indentation for `condp` is `[[:block 2]]`. The behavior you're seeing is correct for this rule.

To explain further, this rule means that the first two arguments have normal indentation, and all subsequent arguments are indented by a fixed 2 spaces.

**Comment by finalfantasia** [comment]
Ah, I see. I don’t think I fully understood the way `block` rules work.

Unless I’m missing something, I don’t see it mentioned anywhere in README.md what rules apply to the “specially” treated form arguments (in the case of `condp`, the first two, especially the indentation behavior for the 2nd form argument) when the threshold is not broken. Would it be helpful to clarify that by including an example with `condp` along with your explanation?

Thanks for the prompt response!
