### ISSUE TITLE
Fails to compile on leiningen 2.3.4

### ISSUE THREAD

**Issue by GregorStocks** [weavejester/cljfmt#24]
It looks like the `warn` function used at https://github.com/weavejester/cljfmt/blob/ec938edb98c58c3702959307fde7670f73f75917/lein-cljfmt/src/leiningen/cljfmt.clj#L61 wasn't introduced until recently - leiningen 2.3.4, which was the most recent version under a year ago, doesn't have it, which makes the instructions in the README fail with a pretty opaque error message. I think switching to "info" would be good enough, that function seems to be much older.

**Comment by weavejester** [comment]
`info` doesn't do the same thing as `warn`. I could use custom versions of those functions, but I'd need a compelling use case. Is there any reason why people shouldn't be using a recent version of Leiningen?

**Comment by GregorStocks** [comment]
Just every programmer's laziness, I guess. If you do want to depend on a newer leiningen I'd at least recommend making it spew a simpler error message in this case (or ideally specifying the lein dependency in the project.clj, but as far as I can tell you can't quite do that with lein plugins).

**Comment by weavejester** [comment]
I don't want to get into a position where I'm testing this plugin against multiple versions of Leiningen, or adding custom code to check for certain versions of Leiningen. But I can add a notice to the README informing people that this has only been tested on Leiningen 2.5, and that YMMV if you are still using an older version.

**Comment by GregorStocks** [comment]
Good enough!
