### ISSUE TITLE
indent matching support for string regex

### ISSUE THREAD

**Issue by BrunoBonacci** [weavejester/cljfmt#244]
Hi,

in the documentation it is stated that symbols can be matched via reg-ex patterns like:

``` clojure
:cljfmt {:indents ^:replace {#".*" [[:inner 0]]}}
```

`cljfmt` is embedded in many other tools. For example `clojure-lsp` embeds `cljfmt` for source code formatting. (see https://clojure-lsp.io/settings/)

The configuration for `cljfmt` is often provided as EDN file, however [EDN doesn't support regular expressions](https://github.com/edn-format/edn/issues/26).

I'd like to suggest that a pattern for indents can be provided as a regular string as well, so for example the above configuration could be provided as following as well:

``` clojure
:cljfmt {:indents ^:replace {".*" [[:inner 0]]}}
```

The change to the [indent-matches?](https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/core.cljc#L227-L229) function is fairly simple:

``` clojure
(defn- indent-matches? [key sym]
  (if (symbol? sym)
    (cond
      (symbol? key)  (= key sym)
      (pattern? key) (re-find key (str sym))
      (string? key)  (re-find (re-patten key) (str sym)))))
```

And it would allow defining patterns in configurations which currently isn't possible.

**Comment by weavejester** [comment]
Resolved by #308.
