### ISSUE TITLE
[[:block]] misbehavior

### ISSUE THREAD

**Issue by introom** [weavejester/cljfmt#249]
Given
```
(foo
 bar baz bang)
```
and 
```
{foo [[:block 1]]}
```
cljfmt formats it to
```
(foo
 bar baz bang)
```
instead of
```
(foo
  bar baz bang)
```

**Comment by weavejester** [comment]
That's the intended behaviour for `[:block 1]`. You want `[:block 0]` if you want it to indent with zero arguments. See the README for more details.

**Comment by introom** [comment]
Based on this doc: https://github.com/weavejester/cljfmt#block-rules
```
The :block rule supports indenting to the first form argument. It has a single rule type argument:

line-arg-count-threshold - when there are more than this many form arguments on the same line as the form symbol, eligible form arguments on subsequent lines are indented to align with the first form argument. Otherwise, two space inner indentation is applied.
```

Given 
```
(foo
 bar baz bang)

{foo [[:block 1]]}
```
Line-arg-count-threshold is 1 here.

The argument count on the foo line is 0. Since 0 < 1, so two space inner indentation shall be applied.
The desired output should have been:
```
(foo
  bar baz bang)
```

Instead of
```
(foo
 bar baz bang)
```

**Comment by weavejester** [comment]
Ah, the updates to the README have resulted in the wrong documentation. Let me fix that.

**Comment by lread** [comment]
Sheesh, who made those updates anyway, eh? 🙂 
It was my best stab at the time James, lemme know if you need help with a doc fix.

**Comment by weavejester** [comment]
> Sheesh, who made those updates anyway, eh? 🙂 It was my best stab at the time James, lemme know if you need help with a doc fix.

The documentation you were working from was flawed, so it was ultimately my fault :)

**Comment by weavejester** [comment]
README has now been fixed.
