### ISSUE TITLE
Tries to delete space before ;; before lines preceding closing braces

### ISSUE THREAD

**Issue by GregorStocks** [weavejester/cljfmt#25]
Cljfmt tries to delete the space before a ;; on the line before a closing bracket, e.g.:

```
[gregor@dev-1386282934] /mnt/gregor/code/cljfmt-badness {master}% lein cljfmt check
src/cljfmt_badness/core.clj has incorrect formatting:
--- a/src/cljfmt_badness/core.clj
+++ b/src/cljfmt_badness/core.clj
@@ -4,6 +4,6 @@
   "I don't do a whole lot."
   [x]
   (let [x [1 2 ;; test1
-           2 3 ;; test2
-           ]])
+           2 3;; test2
+]])
   (println x "Hello, World!"))

1 file(s) formatted incorrectly
```

I'm not sure what the best way to indent the ]]) line is, but I don't think there's any reason to delete the space.

Repro: git clone https://github.com/GregorStocks/cljfmt-badness and run lein cljfmt check

**Comment by weavejester** [comment]
It seems like the thing to do is to ignore whitespace before an ending bracket if a comment precedes it. So:

```clojure
(foo x ; a
     y ; b
     )
```

Then as a future feature we can add a rule that corrects the comment position:

```clojure
(foo x ; a
     y) ; b
```

**Comment by GregorStocks** [comment]
Sounds good to me.
