### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by or** [weavejester/cljfmt#254]
As most users, I use linters and formatters mainly in my editor, but also to check or fix a larger code base at the command line or in workflows.
For both of those usages performance is a factor, so I've been trying to reduce `cljfmt` start-up and run time.

- I've experimented with using `pmap` to process multiple files for `fix`, and that sped up fixing a largeish directory by a factor of 2-3, so I think a `--parallel` option would be useful, would you consider a PR for that feature?
- the plugin to create a native image currently has a bug that prevents the `:jvm-opts` specified for it to be used (see https://github.com/taylorwood/lein-native-image/pull/8), if those flags are used, then the executable is about 20% faster on my machine (with GraalVM CE or EE); I only mention this here as a heads up, as I hope the plugin will be fixed soon, but if that takes longer than expected it might be worth to use the workaround
- a small performance improvement for native-image is not using `read-string` here: https://github.com/or/cljfmt/blob/da37b7aef08be99dbb8e2e8772d95308150d7adb/cljfmt/src/cljfmt/main.clj#L146, which is done to allow `.clj` files for indents and aliases; a little surprisingly this doubles the size of the native-image executable and removing it improves performance by about 4-5% - I realize that's not huge, but would you consider a build flag that turns off .clj support?

The largest improvement is using GraalVM EE, which has nothing to do with `cljfmt`, but it almost doubles the speed out of the box, and even there the `jvm-opts` and clj-support removal have a noticeable impact. For the largest CLJS file in my project the current master took a median of 556ms to fix an already formatted file (with the various options I use), with the changes it's down to 443ms. With GraalVM EE this crumbles to 258ms.
These are all acceptable numbers, but I think it's worth optimizing this as much as possible, so it becomes unnoticeable when used in an on-save handler in the editor.

For reference:
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">version</th>
<th scope="col" class="org-left">GraalVM</th>
<th scope="col" class="org-left">size in MB</th>
<th scope="col" class="org-right">&#x2013;help</th>
<th scope="col" class="org-right">check in ms</th>
<th scope="col" class="org-right">fix in ms</th>
<th scope="col" class="org-right">speed %</th>
<th scope="col" class="org-left"> EE speed %</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">master</td>
<td class="org-left">CE 22.1.0 Java 17</td>
<td class="org-left">37</td>
<td class="org-right">91</td>
<td class="org-right">568</td>
<td class="org-right">556</td>
<td class="org-right">100</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">jvm-opts</td>
<td class="org-left">CE 22.1.0 Java 17</td>
<td class="org-left">36</td>
<td class="org-right">85</td>
<td class="org-right">473</td>
<td class="org-right">464</td>
<td class="org-right">120</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">jvm-opts, no-clj</td>
<td class="org-left">CE 22.1.0 Java 17</td>
<td class="org-left">17</td>
<td class="org-right">80</td>
<td class="org-right">451</td>
<td class="org-right">443</td>
<td class="org-right">126</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>

<tbody>
<tr>
<td class="org-left">master</td>
<td class="org-left">EE 22.1.0 Java 17</td>
<td class="org-left">36</td>
<td class="org-right">61</td>
<td class="org-right">320</td>
<td class="org-right">314</td>
<td class="org-right">177</td>
<td class="org-left">100</td>
</tr>

<tr>
<td class="org-left">jvm-opts</td>
<td class="org-left">EE 22.1.0 Java 17</td>
<td class="org-left">37</td>
<td class="org-right">56</td>
<td class="org-right">277</td>
<td class="org-right">267</td>
<td class="org-right">208</td>
<td class="org-left">118</td>
</tr>

<tr>
<td class="org-left">jvm-opts, no-clj</td>
<td class="org-left">EE 22.1.0 Java 17</td>
<td class="org-left">19</td>
<td class="org-right">54</td>
<td class="org-right">265</td>
<td class="org-right">258</td>
<td class="org-right">216</td>
<td class="org-left">122</td>
</tr>
</tbody>
</table>

I haven't tried a comparison with the leiningen plugin, but perhaps a section in the README on these options (lein, GraalVM CE, and EE) and how they compare could be useful for anyone wanting to adopt `cljfmt` and having performance concerns.

**Comment by weavejester** [comment]
Sure, I'll accept any well written PR that improves performance.
