### ISSUE TITLE
Update rewrite-clj dep

### ISSUE THREAD

**Issue by bbatsov** [weavejester/cljfmt#26]
The latest version drops two problematic deps (fast-zip and potemkin) which makes it easier to embed rewrite-clj and cljfmt into dev tools (like CIDER), without introducing dep conflicts. See https://github.com/xsc/rewrite-clj/issues/26 for details.

**Comment by bbatsov** [comment]
Thanks!

**Comment by bbatsov** [comment]
Let me know when you cut a new release.

**Comment by weavejester** [comment]
Just released 0.1.9.
