### ISSUE TITLE
Remove trailing whitespace not working as expected

### ISSUE THREAD

**Issue by diegovdc** [weavejester/cljfmt#265]
It is neither removing whitespace at the end of a file, not removing commas (for example in maps). 

Steps to reproduce

This `example.clj`:
```clj
(ns example)



{:a 1,
 :b 2}





```

Becomes:
```clj
(ns example)

{:a 1,
 :b 2}





```
When using `clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.8.0"}}}'  -m cljfmt.main fix example.clj`.

But I would expect:

```clj
(ns example)

{:a 1
 :b 2}
```

**Comment by weavejester** [comment]
Apologies for missing this last year.

`:remove-trailing-whitespace?` removes trailing spaces and tabs in lines. It doesn't remove trailing commas, and it doesn't remove blank lines at the end of the file.
