### ISSUE TITLE
Feature request: indent rule for all unspecified functions

### ISSUE THREAD

**Issue by sirmspencer** [weavejester/cljfmt#266]
Allow an indent rule to be created for all functions / macros that are not defined [here](https://github.com/weavejester/cljfmt/blob/master/cljfmt/resources/cljfmt/indents/clojure.clj) or in the :indents map.  

Half of our team is using Cursive, which favors this form for multi line function calls. Note the two space indent.
```
(some-fn
  (another -fn)
  arg2
``` 
The indent rule to replace all doesnt work ~~for two reasons. 1) regex is invalid when using a .cljfmt.edn file, and 2) Cursive follows the same indent rules for almost every rule that is a default for cljfmt.~~ because Cursive only uses the default 2 space indent for unknown functions.  Globally changing all forms to `[:block 0]` changes more code than not. Something like this maybe

```
{:indents {defstate [[:block 2]]}
  :list-indent 2}
```

**Comment by leafgarland** [comment]
Thanks for explaining why my attempt at this with a regex doesn't work (it's in a config.edn file).

I would also like to set a default for all unspecified fns.

**Comment by sirmspencer** [comment]
@leafgarland Where you able to set that regex rule, but then also other rules that supersede the regex?

**Comment by weavejester** [comment]
You should be able to add it to your configuration, so in `cljfmt.edn` or `cljfmt.clj`, or in your Leiningen `project.clj` file. See the README for an explanation of how to configure.
