### ISSUE TITLE
Could we have a new release for native-image fix and latest indents?

### ISSUE THREAD

**Issue by grzm** [weavejester/cljfmt#272]
We're currently using cljfmt native-image locally, which we build by pulling master as it includes the native-image build fix (19e0861d109ba3e89b8ebedbb45fdf564b7fd659). However, in CI where we run a cljfmt check, we don't build the native image (or have it pre-compiled) cljfmt so we rely on the jar. Currently the jar (0.8.2) does not have all of the default indents that are in HEAD (namely b0f7f86a548115ea46a9d91c7f12fe79e376b940 delay indents).

Would you please release a new version of cljfmt which includes these fixes?

**Comment by weavejester** [comment]
Done. Apologies for the delay.

**Comment by grzm** [comment]
No apologies necessary. Thanks for the quick turnaround! You rock! :) 🎸
