### ISSUE TITLE
Options aren't working when running cljfmt.main

### ISSUE THREAD

**Issue by jetmind** [weavejester/cljfmt#278]
The [code](https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/main.clj#L202) suggests some options could be used with cljfmt.main but it doesn't seem to work, e.g.

```
› clojure -Sdeps '{:deps {cljfmt/cljfmt {:mvn/version "0.9.0"}}}' -M -m cljfmt.main check --no-remove-consecutive-blank-lines
[Unknown option: "--no-remove-consecutive-blank-lines"]
```

Am I missing something?

**Comment by weavejester** [comment]
I don't get that output when running that line of code. For me, it runs correctly, even on a clean machine. What shell are you using? Could there be something in your dependency cache that's messing things up somehow?

**Comment by jetmind** [comment]
I didn't realize I had dependency on old version of tools.cli in project I ran command from.  Everything works as expected now, thank you
