### ISSUE TITLE
Regression in 0.1.8

### ISSUE THREAD

**Issue by bbatsov** [weavejester/cljfmt#28]
The following code:

```clojure
( let [x 3
    y 4]
  (+ (* x x
  )(* y y)
  ))
```

is now indented as:

```clojure
(let [x 3
      y 4]
  (+ (* x x
        )(* y y)
     ))
```

I'm using `reformat-string` without custom config.

Used to indented properly in 0.1.7.

**Comment by weavejester** [comment]
Thanks for the report. Looks like 76cdf10 broke it. I'll work on a fix.
