### ISSUE TITLE
ignoring defaults

### ISSUE THREAD

**Issue by ztellman** [weavejester/cljfmt#29]
Hey, this is a really great tool.  I use a somewhat non-standard indentation scheme which is basically

```clj
:cljfmt {:indents {#".*" [[:inner 0]]}}
```

But unfortunately, in order to override the defaults I need to explicitly specify symbols for everything.  If there were some way to disable the defaults, that would be very helpful.

**Comment by weavejester** [comment]
Perhaps we could take a page from Leiningen's playbook and support metadata hints, e.g.

```clojure
:cljfmt {:indents ^:replace {...}}
```

I have a standalone [meta-merge library](https://github.com/weavejester/meta-merge) that would work. It would introduce a new dependency, but meta-merge isn't dependant on anything else and is unlikely to change, and if it does become a problem we can inline it.

**Comment by ztellman** [comment]
Sounds good to me.

**Comment by weavejester** [comment]
Is there any other metadata we'd need to support other than `^:replace`? If not, we could skip the meta-merge library and make it a single check.

**Comment by ztellman** [comment]
I don't think the converse `^:displace` makes much sense, so maybe not?

**Comment by weavejester** [comment]
@ztellman this functionality has been added to 0.3.0
