### ISSUE TITLE
Babashka compatibility

### ISSUE THREAD

**Issue by borkdude** [weavejester/cljfmt#292]
It seems `cljfmt.core` is compatible with babashka:

``` clojure
bb -Sdeps '{:deps {cljfmt/cljfmt {:mvn/version "0.9.2"}}}' -e "(require '[cljfmt.core]) (println (cljfmt.core/reformat-string (slurp \"/tmp/dude/foo.cljs\")))"
```

I think with a few minor tweaks we can make the main namespace compatible too, except for the `diff` functionality since it relies on a Java library. If there's any interest in this, I can make a PR.

**Comment by weavejester** [comment]
Sure, that sounds useful.

**Comment by lread** [comment]
For ongoing compatibility, do we want to add bb tests to cljfmt?
If so, I could help with that.

**Comment by weavejester** [comment]
Yes, that might be useful. I've been considering adding some shell tests as well, since there have been a few bugs with running cljfmt via the CLI and Lein wrappers.
