### ISSUE TITLE
CLJS tests are failing

### ISSUE THREAD

**Issue by borkdude** [weavejester/cljfmt#296]
Despite `lein test` returning a 0 exit code, it seems that the CLJS tests are failing.

<img width="1155" alt="Screenshot 2023-02-02 at 20 28 20" src="https://user-images.githubusercontent.com/284934/216430909-3bd12a00-ca44-4fcf-b6bf-100965c9a39d.png">

I'll follow up with a PR since I was the one who broke this, although I think the test runner should have exited with a non-zero exit code.

**Comment by weavejester** [comment]
That's strange. [The testrunner](https://github.com/weavejester/cljfmt/blob/7dfd55d5dd0756f30311a90f206c2dd32e56d18b/cljfmt/test/cljfmt/test_runner.cljs#L8) should end the process with an error code if there are any failures. I'll look into this, and thanks for the fix.
