### ISSUE TITLE
Should regular expressions in indent rules be able to target keywords?

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#298]
Hi!

With an indents spec like so:

```clojure
{#"\S+" [[:inner 0]]}
```

Formatting:

```clojure
(and a
        b
  ) 

(:require []
             []
 )
```

Yields:

```clojure
(and a
  b)

(:require []
          [])
```

Is this by design?

I'm wondering because in Calva we have an indenter that is configured with `cljfmt` indent rules, and it currently indents the `:require` forms using `[[:inner 0]]`:

* https://github.com/BetterThanTomorrow/calva/issues/2044

**Comment by weavejester** [comment]
Currently the indent rules are just for symbols. We'd need to expand the configuration rules to make indents work with keywords.

**Comment by PEZ** [comment]
Thanks! Can I then assume that keywords always should be indented according to `[:block 0]`?

**Comment by weavejester** [comment]
Not exactly: they're indented according to the [default behavior](https://github.com/weavejester/cljfmt#default-behavior).

**Comment by PEZ** [comment]
Thanks again! 🙏  I'll just skip applying any rules when it comes to keywords then.
