### ISSUE TITLE
Installing to ~/.lein/profiles.clj causes dependency issue with rewrite-clj

### ISSUE THREAD

**Issue by jballanc** [weavejester/cljfmt#3]
If the plugin is installed via Leiningen's local profiles (i.e. `~/.lein/profiles.clj`), there is an issue locating `rewrite-clj`:

```
Caused by: java.io.FileNotFoundException: Could not locate rewrite_clj/node__init.class or rewrite_clj/node.clj on classpath:
```

**Comment by weavejester** [comment]
It's likely you have another plugin or dependency in your `profiles.clj` file that pulls in an older version of rewrite-clj, and this is conflicting with cljfmt.

**Comment by jballanc** [comment]
Ah, indeed! Ironically enough, it was `lein-ancient` that had the outdated version. Apologies for the noise.

**Comment by arrdem** [comment]
FWIW `lein-ancient` dropped a new version yesterday. That may help solve your problem.
