### ISSUE TITLE
`lein cljfmt check` ignores `.cljfmt.edn` configurations

### ISSUE THREAD

**Issue by raycheung** [weavejester/cljfmt#301]
Calling `lein cljfmt check` only reads configurations written in `project.clj`, not `.cljfmt.edn` / `.cljfmt.clj` files in directory hierarchy.

**Comment by weavejester** [comment]
Yes, by design.

**Comment by raycheung** [comment]
Oh, may I know the reason behind please?
Also, if so, when would the .cljfmt.edn be read?

I'm asking as I'm a vim-cljfmt user, but it couldn't have a way to integrate with respect to a custom config. The options computed in the cljfmt.main are private.

I would like to make it work as I love cljfmt but it doesn't integrate with my vim too well at the moment.

**Comment by weavejester** [comment]
The `.cljfmt` files are designed as ways of configuring cljfmt when used as a standalone tool. When used via Leiningen it uses Leiningen's own configuration system (so `project.clj`, `profiles.clj`, etc.). Can you explain your use-case? I'm not sure why you'd want to use Leiningen to start cljfmt, but simultaneously not use Leiningen to configure cljfmt.

**Comment by raycheung** [comment]
Thanks explaining.
The way current I'm using cljfmt is via vim, more precisely via vim-cljfmt. It does a quite indirect way to integrate.
More precisely, at https://github.com/venantius/vim-cljfmt/blob/master/plugin/cljfmt.vim#L41 , it builds a clojure string which is evaluated against the current editing file (buffer) in vim, then pop it back as the reformatted.

The issue is that if I want to configure any custom indents or so, there is no way the vim-cljfmt could easily work it out the final config (options) to pass to cljfmt.

It isn't a cljfmt issue per se. However it would be much nicer if there is a mechanism to trigger the reformat with all the hierarchical configured options working out.

**Comment by weavejester** [comment]
Thanks for explaining. In this case, however, it looks like vim-cljfmt doesn't use the `.cljfmt.*` files for configuration?

**Comment by raycheung** [comment]
You're right, it doesn't. I'm trying to make it works.
Could you advise which function call sequence would work?
Reading cljfmt.main, it appears to me the `.cljfmt.*` are read only in the `-main` with a series of private functions, and I couldn't obtain the result outside that function.

**Comment by weavejester** [comment]
We'd likely have to write a public API for it, as functions like `load-configuration` are private, as you point out.

**Comment by sirmspencer** [comment]
I have a different use case for this same request.  In VSCode and emacs have can use lsp to auto format on save.  lsp is reading the .cljfmt file for configuration.  Other devs in our group need to be able to run the shell command to format.  With only a projects.clj, there is two copies of the formatting config that have to be maintained. 

How about a flag in project.clj to read the file?
`:cljfmt {:from-file? true}`

**Comment by weavejester** [comment]
Maybe `:load-dotfile?`, to be more specific. But I'm fine with this in principle.

**Comment by sirmspencer** [comment]
Is there something you can point me to for a dev set up on this?  Ive never worked on a lein plugin before.

**Comment by weavejester** [comment]
> Is there something you can point me to for a dev set up on this? Ive never worked on a lein plugin before.

You just need Leiningen. If you run `lein cljfmt` in the `lein-cljfmt` directory, you'll run the local copy of the plugin.
