### ISSUE TITLE
"Invalid token :mm/dd/yyyy"

### ISSUE THREAD

**Issue by kstephens** [weavejester/cljfmt#31]
This might be a clojure.tools bug, however:

lein cljfmt fails on keyword ":mm/dd/yyyy", which parses in clojure.

Example:

```clojure
 #\ cat cljfmt-invalid-token.clj
(def token :mm/dd/yyyy)
```

```shell
 #\ lein cljfmt check cljfmt-invalid-token.clj
clojure.lang.ExceptionInfo: Invalid token: :mm/dd/yyyy
 at clojure.core$ex_info.invoke (core.clj:4403)
    clojure.tools.reader.reader_types$reader_error.doInvoke (reader_types.clj:337)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.tools.reader.edn$read_keyword.invoke (edn.clj:268)
    clojure.tools.reader.edn$read.invoke (edn.clj:369)
    clojure.tools.reader.edn$read.invoke (edn.clj:357)
    clojure.tools.reader.edn$read.invoke (edn.clj:354)
    rewrite_clj.parser.keyword$parse_keyword.invoke (keyword.clj:18)
    rewrite_clj.parser.core$eval3255$fn__3256.invoke (core.clj:95)
    clojure.lang.MultiFn.invoke (MultiFn.java:227)
    rewrite_clj.reader$read_with_meta.invoke (reader.clj:117)
    rewrite_clj.parser.core$parse_next.invoke (core.clj:34)
    rewrite_clj.parser.core$parse_delim$fn__3225.invoke (core.clj:42)
    rewrite_clj.reader$read_repeatedly$fn__3124.invoke (reader.clj:126)
```

**Comment by cichli** [comment]
I think that's not a valid keyword (even though the current implementation of Clojure allows it). This is a case of `tools.reader` agreeing with the documentation and `LispReader.java` being more lax than the documentation.

See http://clojure.org/reader - specifically the notes on symbol and keyword literals: `... '/' has special meaning, it can be used once in the middle of a symbol ...` and `Keywords are like symbols ...`.

[This JIRA issue](http://dev.clojure.org/jira/browse/CLJ-1527) is related.

**Comment by weavejester** [comment]
Yep, that isn't a valid keyword. Clojure's default reader doesn't have many checks, particularly when it comes to symbols and keywords.

**Comment by kstephens** [comment]
Thank you for the clarification.  I'm fairly new to Clojure -- it's not Scheme!  :)
