### ISSUE TITLE
Change 11 to be non breaking

### ISSUE THREAD

**Issue by sirmspencer** [weavejester/cljfmt#316]
~~Is there a way to backport this feature to 10.7 to give us more time to work on updating to the 11 series?~~

**Comment by sirmspencer** [comment]
Or have 11 be non breaking by keeping indents as is and adding :override-indents as the new key.

**Comment by weavejester** [comment]
Can you describe why there's difficulty updating? The only thing you should need to do is to rename the `:indents` key in your configuration to `:extra-indents`.

**Comment by sirmspencer** [comment]
> Can you describe why there's difficulty updating? The only thing you should need to do is to rename the `:indents` key in your configuration to `:extra-indents`.

The problem is keeping all the IDEs / tooling on the same version.  I can't use 11, until clojure-lsp updates to 11.  We have a large team on different tools, I don't know when all their tools will adopt 11 either.

**Comment by weavejester** [comment]
I did consider the non-breaking option you describe, and it would have been an obvious solution if cljfmt was at a stable release. However, the whole point of pre-1.0 releases is to allow the API to change, and it didn't seem correct to compromise for a less consistent syntax while cljfmt is still unstable and has no backward compatibility guarantees.

I can backport the `#re` change easily enough to 0.10.7. I could also investigate adding some temporary version key to the configuration that would turn on legacy behaviour.

**Comment by sirmspencer** [comment]
> However, the whole point of pre-1.0 releases is to allow the API to change, and it didn't seem correct to compromise for a less consistent syntax while cljfmt is still unstable and has no backward compatibility guarantees.

That's fair, but know that cljfmt is the most widely used formatter.  I could only find itellij with cursive that uses a different formatter.

**Comment by sirmspencer** [comment]
What about leaving `:indents` the same for a few releases the same, and using `:merge-indents` and `:override-indents` to be even more specific?  I don't personally see that `:indents` and `:extra-indents` is any more clear than keeping the existing `:indents` with something like `:override-indents`.  `:indents` on its own isn't describing a behavior the same way using `:merge-indents` and `:override-indents` would.

**Comment by sirmspencer** [comment]
> I can backport the #re change easily enough to 0.10.7. I could also investigate adding some temporary version key to the configuration that would turn on legacy behaviour.

This helps me at least in the short term, and might give enough room to coordinate updating to 11.

**Comment by weavejester** [comment]
Understood. However now that 0.11 has been released, we can't return to the old behaviour without breaking compatibility *again*, which would just compound the problem.

The reason for calling the keys `:indents` and `:extra-indents` is that this is the convention used in deps.edn, e.g. with `:extra-deps` and `:extra-paths`. It's also more consistent with the other configuration keys, where specifying a value overrides the key's default.

**Comment by sirmspencer** [comment]
> Understood. However now that 0.11 has been released

only yesterday if you act fast.

**Comment by sirmspencer** [comment]
> The reason for calling the keys :indents and :extra-indents is that this is the convention used in deps.edn, e.g. with :extra-deps and :extra-paths. It's also more consistent with the other configuration keys, where specifying a value overrides the key's default.

Fair enough.

**Comment by weavejester** [comment]
I've added `:legacy/merge-indents?` option for compatibility. Adding that option should allow configurations to work for both 0.11 and 0.10.

**Comment by sirmspencer** [comment]
Great, I'll give it a try.

**Comment by sirmspencer** [comment]
Looks good so far, thanks!
