### ISSUE TITLE
Error w/ Installation

### ISSUE THREAD

**Issue by drusellers** [weavejester/cljfmt#32]
When I run `lein` to see all commands I get:

```
leiningen.cljfmt  Problem loading: java.io.FileNotFoundException: Could not locate rewrite_clj/node__init.class or rewrite_clj/node.clj on classpath: , compiling:(cljfmt/core.clj:1:1)
```
I'm sure I'm doing something wrong. 

Lein 2.5
[lein-cljfmt "0.1.10"]

**Comment by expez** [comment]
If you're using it, try bumping lein ancient to the latest version.  Both libs depend on `rewrite-clj`.

**Comment by weavejester** [comment]
You're running into a dependency conflict. See issue #12.

**Comment by drusellers** [comment]
That did it! Thanks.
