### ISSUE TITLE
Formatting croaks on some new Clojure 1.12 syntax

### ISSUE THREAD

**Issue by PEZ** [weavejester/cljfmt#355]
Hi!

The new Clojure 1.12 syntax for array classes makes clj-fmt sad:

```clojure
  #_{:deps {dev.weavejester/cljfmt {:mvn/version "0.12.0"}}}
  (require '[cljfmt.core :as fmt])
  (fmt/reformat-string "^[Long] a")
  ;;=> "^[Long] a"
  (fmt/reformat-string "^Long/1 a")
  ;;=> Execution error (ExceptionInfo) at clojure.tools.reader.impl.errors/throw-ex (errors.clj:34).
  ;;   Invalid symbol: Long/1.
```

It starts working if I make it use [rewrite-clj 1.1.48](https://github.com/clj-commons/rewrite-clj/blob/main/CHANGELOG.adoc#v1148---2024-08-15).

**Comment by weavejester** [comment]
Updated the dependencies. I'll release a new version soon.
