### ISSUE TITLE
does not work from ~/.lein/profiles.clj

### ISSUE THREAD

**Issue by timothypratley** [weavejester/cljfmt#38]
when using ~/.lein/profiles.clj:

$ lein cljfmt fix foo.edn

`clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate rewrite_clj/node__init.class or rewrite_clj/node.clj on classpath: , compiling:(cljfmt/core.clj:1:1)`

workaround:
add to {:user {:plugins
                    [rewrite-clj "0.4.12"]

**Comment by weavejester** [comment]
See issue #12. It's because you have another plugin that uses an older version of rewrite-clj, and it's overriding the later version in cljfmt.

**Comment by timothypratley** [comment]
gotcha thanks yes, upgrading ancient to 0.6.6 resolved the issue also
