### ISSUE TITLE
Comment immediately before a method causes indent

### ISSUE THREAD

**Issue by jballanc** [weavejester/cljfmt#4]
Running `cljfmt` against the following suggests that the method should be indented 1 space:

```clj
(ns foo.core)

;; Just a comment...
(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
```

I'm fairly certain that top-level methods shouldn't be indented, even if following a comment. If anything, maybe the correct suggestion would be to introduce a blank-line (but even that I'm not so sure about).

**Comment by jballanc** [comment]
It's worth noting that this also affects two consecutive lines of top-level comments:

```clj
;; Comment line 1
;; Comment line 2
```

**Comment by weavejester** [comment]
Thanks for the bug report. I'm currently working on fixing the indentation around comments.

**Comment by muhuk** [comment]
This might also be related. It formats this:

```clojure
(defn f
  ([_]
   (assert true true)
   (binding [foo bar]
     (prn :debug))))
```

as:

```clojure
(defn f
  ([_]
   (assert true true)
    (binding [foo bar]
      (prn :debug))))
```

**Comment by weavejester** [comment]
@muhuk looks like that bug has a slightly different cause, even though it looks similar. If you have time, could you open up a separate issue for it?

**Comment by muhuk** [comment]
No problem. I've created #10.
