### ISSUE TITLE
Exception in thread "main" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by AsaAyers** [weavejester/cljfmt#40]
I'm new to Clojure. As far as I can tell this is the minimum `project.clj`:

```
(defproject euler "0.2.0")
```

When I run `lein cljfmt fix` I get a StackOverflowError. If I specify the files to fix it works.

I installed cljfmt by adding it to my `~/.lein/profiles.clj `

```
{:user {:plugins [[lein-exec "0.3.5"] [lein-cljfmt "0.1.10"]]}}
```

**Comment by weavejester** [comment]
Are you running into issue #33?

**Comment by AsaAyers** [comment]
You're correct. This is a duplicate issue.

Since I'm starting to learn Clojure I'm messing around and haven't yet learned the "proper" way to setup a project. So I just have a few files in a folder that I'm experimenting with. At this point I have no idea why `:source-paths` matters.

**Comment by weavejester** [comment]
`:source-paths` define the paths of your source code. It defaults to `["src"]`. You may be running into #33 if you've redefined this value, or if you do not have a `src` directory.
