### ISSUE TITLE
EDN file for project-wide configuration?

### ISSUE THREAD

**Issue by sgrove** [weavejester/cljfmt#41]
I'd love to be able to add a .cljfmt.edn file to my projects, specifying various forms of let alignment (e.g. #36 ) or strict whitespace removal (e.g. #39), and have all of the contributors format their PR's automatically so everything lines up nicely with the project's style guidelines (also, upon style changes, there's a single place to update and the entire codebase can be reformatted).

Actually, I'd enjoy this even more when contributing to other projects, as right now I have tons of issues with `aggressive-indent-mode` and whitespace problems, and end up having to link to the whitespace-disabled comparison view for PR's.

I'd like to be very aggressive about it (for my own personal/work projects), such that every character is placed according to format rules. Happy to write the rules once and then never deal with whitespace merges again.

**Comment by weavejester** [comment]
I'm not sure I understand the purpose of this suggestion. If you're using lein-cljfmt, then you can already configure it via the project file. If you're using cljfmt straight, then you can configure it via an argument.

**Comment by sgrove** [comment]
Yes, that's fair, I slightly misunderstood the project.clj formatting option. Everything else is just more features for controlling the formatting. Sorry about that - closing this.
