### ISSUE TITLE
Wrong indentation on nested forms within letfn

### ISSUE THREAD

**Issue by Malabarba** [weavejester/cljfmt#42]
Note how cljfmt indents [this `str` call](https://github.com/Malabarba/cider-nrepl/blob/master/src/cider/nrepl/middleware/debug.clj#L18). I believe the second line should be indented by a couple more spaces, to align with the arguments above.

**Comment by weavejester** [comment]
I believe this is a problem with `letfn`, rather than `str`. The indentation of the function blocks isn't limited to the first vector, as it should be.
