### ISSUE TITLE
cond-> should be indented like cond

### ISSUE THREAD

**Issue by Malabarba** [weavejester/cljfmt#44]
I believe `cond->` and `cond->>` should be indented like the following, 

    (cond->> [:a :b :c]
      (pred?) (remove #{:a})
      true    (vec))

but cljfmt indents them like this:

    (cond->> [:a :b :c]
             (pred?) (remove #{:a})
             true    (vec))

For instance, [see here](https://github.com/clojure-emacs/cider-nrepl/pull/236/files#diff-0d65c570bef3dbf4640690a252e06f28R224).

**Comment by weavejester** [comment]
cljfmt does do this for `cond->`, but `cond->>` is missing from the indentation rules.

**Comment by weavejester** [comment]
Fixed in 0.2.1.

**Comment by Malabarba** [comment]
Thanks @weavejester
