### ISSUE TITLE
Usage with cider tutorial

### ISSUE THREAD

**Issue by Immortalin** [weavejester/cljfmt#47]
Hi, can you create a tutorial for auto-formatting on save for cider?

**Comment by weavejester** [comment]
I think that's probably something for Cider's documentation.

**Comment by Immortalin** [comment]
Cider is listed under editor support though

**Comment by weavejester** [comment]
That's because Cider uses cljfmt. It's not because cljfmt *itself* supports Cider. There's no elisp in the cljfmt repository.

**Comment by Immortalin** [comment]
interesting. How do you call cljfmt from cider then?

**Comment by weavejester** [comment]
It doesn't appear to be documented in the Cider README yet, but `cider-format-region`, `cider-format-defun` and `cider-format-buffer` are the elisp functions you're looking for.

**Comment by Immortalin** [comment]
Thank you!
