### ISSUE TITLE
Indentation of midje forms?

### ISSUE THREAD

**Issue by timvisher** [weavejester/cljfmt#48]
I think it's accepted to format midje forms like so:

```clojure
(facts "about indenting midje facts"
  (fact "see how i'm indented like a let?"))
```

cljfmt seems to want to indent it like this

```clojure
(facts "this is how cljfmt does it"
       (fact "see how i'm indented like a function?"))
```

Where's the discrepancy lie here?

**Comment by weavejester** [comment]
cljfmt has no special rules for Midje, but it's easy to add custom indentation rules. In this case, you can just add to your cljfmt options:

```clojure
{:indents {facts [[:inner 0]]}}
```

There's an explanation in the README.

**Comment by timvisher** [comment]
:+1:
