### ISSUE TITLE
Could not find project.clj

### ISSUE THREAD

**Issue by spinningarrow** [weavejester/cljfmt#50]
I'm trying to format a single file by running `lein cljfmt check <filename>` but it keeps telling me that it `Couldn't find project.clj, which is needed for cljfmt`. Why does it need a `project.clj` even for a single file?

**Comment by weavejester** [comment]
That's the default for Leiningen tasks, I believe. I'd accept a patch to allow cljfmt to check and fix files without a project file, so long as the files were specified explicitly.
