### ISSUE TITLE
<U+2028> causes exception

### ISSUE THREAD

**Issue by shmish111** [weavejester/cljfmt#51]
Somehow <U+2028> had got into my code (using mac notes I think) this caused cljfmt to throw
`Exception in thread "main" java.lang.AssertionError: Assert failed: (re-matches #"(\s|,)+" s)` and it took me ages to work out why. I don't think it should fail like this. Plus it would be nice if it told you which file failed.

**Comment by weavejester** [comment]
This assertion is from the underlying [rewrite-clj](https://github.com/xsc/rewrite-clj) library, so the best place to raise the issue would be there. Out of interest, did Clojure compile and run your code okay?

**Comment by shmish111** [comment]
Yes it did, thanks I'll speak to them and post the issue on a comment for
history

**Comment by weavejester** [comment]
Should be fixed in rewrite-clj 0.5.0, and cljfmt uses 0.5.2.
