### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by snoe** [weavejester/cljfmt#52]
Hi great tool.

With the very fast startup time of node, a clojurescript (i.e. cljc/reader conditional) port would allow some interesting scripting possibilities with cljfmt. Personally, I'd love to use cljfmt for [my neovim plugin](https://github.com/snoe/clj-refactor.nvim).

I wouldn't mind working on a PR to attempt to add cljs support if you're interested in supporting it. 

Cheers.

**Comment by weavejester** [comment]
I'd welcome ClojureScript support. However, cljfmt relies on rewrite-clj, which is currently only available for Clojure. You'd need to port that, first.

**Comment by snoe** [comment]
Yup, there's an excellent port already https://github.com/rundis/rewrite-cljs

**Comment by weavejester** [comment]
Oh wow, that had completely passed me by. In which case there are no obstacles to ClojureScript support. I think updating the Clojure dependency to 1.7.0 and using `.cljc` would likely be the most idiomatic approach.
