### ISSUE TITLE
formatting custom macro uses is off

### ISSUE THREAD

**Issue by eliben** [weavejester/cljfmt#63]
_Thanks for cljfmt - coming from other languages with such tools, this feels essential_

When I define a new macro:

```
(defmacro when-valid
  ...)
```

And then use it, it makes sense for me to keep some of the arguments on the same line with the macro invocation:

```
(when-valid var set-of-rules
  (do 1...)
  (do 2...))
```

However, cljfmt will reformat this as follows:

```
(when-valid var set-of-rules
            (do 1...)
            (do 2...))
```

Because it wants to line up all the "call" arguments together, similarly to what's done for function calls. But for many macros it's inappropriate, since they have two logically separate sets of arguments

**Comment by expez** [comment]
This probably won't be general enough until cljfmt adds support for an [indentation spec](https://github.com/clojure-emacs/cider/blob/master/doc/Indent-Spec.md).

This would however force cljfmt into doing multiple passes (one to collect metadata to indent properly and then one to actually apply the rules).

**Comment by weavejester** [comment]
You can customise the indentation via your project file, which is documented in the README.

Using var metadata to define indentation is covered by issue #49.

**Comment by eliben** [comment]
Thanks for the quick response
