### ISSUE TITLE
Remove trailing whitespace

### ISSUE THREAD

**Issue by danielcompton** [weavejester/cljfmt#64]
From https://github.com/jaunt-lang/jaunt/commit/b48220d6c096757ef37efce68935dc7aa15e7beb, running `lein cljfmt fix src/clj/clojure/set.clj` doesn't strip the trailing whitespace in `clojure.set`. Using `[lein-cljfmt "0.4.1"]`. Related to #34.

**Comment by arrdem** [comment]
https://github.com/jaunt-lang/jaunt/blob/linter/cljfmt/src/clj/clojure/set.clj

Looks fine to me...

**Comment by danielcompton** [comment]
See https://github.com/jaunt-lang/jaunt/blob/linter/cljfmt/src/clj/clojure/set.clj#L55 for an example.

**Comment by weavejester** [comment]
Was the whitespace already there? cljfmt doesn't yet have a rule for removing whitespace at the end of lines, but shouldn't add any new trailing whitespace.

**Comment by arrdem** [comment]
This is whitespace which was present in the original and was not removed by cljfmt.

**Comment by weavejester** [comment]
That makes sense, then. This isn't a bug so much as a missing feature.
