### ISSUE TITLE
Regular expression reformatting mistakes

### ISSUE THREAD

**Issue by j0ni** [weavejester/cljfmt#66]
cljfmt (actually node-cljfmt, if that's important) made this change:

```diff
-         (re-find #"(?i)RUNNING"))
+         (re-find #"RUNNING"))
```

which is not equivalent. Similarly this:

```diff
-            (re-find #"(?m)^rss\s+(\d+)$")
+            (re-find #"^rss\s+(\d+)$")
```

is likely a breaking change. Is this expected?

It also made this change:

```diff
-  (->> (str/split container-name #"/")
+  (->> (str/split container-name #"\/")
```

which at least seems less destructive.

**Comment by weavejester** [comment]
Thanks for the report. This turns out to be a bug in [rewrite-cljs](https://github.com/rundis/rewrite-cljs). I've opened up new issue at https://github.com/rundis/rewrite-cljs/issues/7.

The Clojure version of cljfmt doesn't suffer from this issue.
