### ISSUE TITLE
Plans for LightTable Plugin? 

### ISSUE THREAD

**Issue by FrankC01** [weavejester/cljfmt#7]
Curious if you are even thinking of integrating into existing IDE tooling?

Thanks
Frank

**Comment by weavejester** [comment]
Maybe eventually, but that'll probably be in another repository.

**Comment by FrankC01** [comment]
Thanks for responding.

Nice job by the way!

-- 


From:  James Reeves <notifications@github.com>
Reply-To:  weavejester/cljfmt
<reply+0052ef1d8c4d1d518e4299cc6967207c02055a2333ce3a5892cf0000000110d8140a9
2a169ce0345a31a@reply.github.com>
Date:  Wednesday, January 21, 2015 at 8:27 PM
To:  weavejester/cljfmt <cljfmt@noreply.github.com>
Cc:  Frank Castellucci <frank.castellucci@axiom1inc.com>
Subject:  Re: [cljfmt] Plans for LightTable Plugin?  (#7)


Maybe eventually, but that'll probably be in another repository.

‹
Reply to this email directly or view it on GitHub
<https://github.com/weavejester/cljfmt/issues/7#issuecomment-70956219> .
