### ISSUE TITLE
Incorrect indentation of reader conditionals.

### ISSUE THREAD

**Issue by carrete** [weavejester/cljfmt#81]
Looks like #80 only fixed half of #59. This still happens:

```clojure
(ns example.core-test
  #?(:clj (:require
           [clojure.test :refer [deftest is]])
          :cljs (:require
                 [cljs.test :refer-macros [deftest is]])))
```

**Comment by weavejester** [comment]
Ah, good catch! That does still need to be solved.

**Comment by arrdem** [comment]
What's the better fix here - hack rewrite-clj to have a better reader-conditional node which exposes the different clauses as if it were a map node or just teach cljfmt about that? Seems like this should probably get fixed on the rewrite-clj side to me...

**Comment by weavejester** [comment]
I think this is something that could be fixed on the cljfmt end of things. cljfmt just needs to treat lists as collections if they succeed a conditional.

**Comment by arrdem** [comment]
Thanks for the quick patch!

**Comment by carrete** [comment]
> Thanks for the quick patch!

Yeah, thanks!

**Comment by carrete** [comment]
And confirmed. This did work. Thanks again!
