### ISSUE TITLE
Undocumented feature: sequence of indentation rules

### ISSUE THREAD

**Issue by MatthewDarling** [weavejester/cljfmt#87]
We're using a macro that wraps ```defrecord```. The cljfmt rule for ```defrecord``` is:

```clojure
[[:block 2] [:inner 1]]
```

However, this doesn't quite produce the indentation I'm looking for, when I apply it to our macro. But the README doesn't spell out what it means to have a sequence of indentation rules, so I'm not too sure how to modify that to work the way I want for our macro.

**Comment by weavejester** [comment]
A sequence of indentation rules is just a way of applying multiple rules.

So in the case of `defrecord`:

```clojure
[[:block 2]   ;; after the second argument indent the form
 [:inner 1]]  ;; also indent any subform one level in
```

So for a record like:

```clojure
(defrecord Foo [x]
  Bar         ;; indent with [:block 2]
  (bar [_]    ;; indent with [:block 2]
    (prn x))) ;; indent with [:inner 1]

**Comment by MatthewDarling** [comment]
Ah, I see, so it's not "apply block then inner in this order" but "both of these things apply".

Your explanation makes sense to me. I think it would make for a good section in the README like "advanced indentation rules" or something.

**Comment by weavejester** [comment]
I'll see about adding one in, though if #49 is solved, the current syntax ceases to be relevant.

**Comment by or** [comment]
I think this was sufficiently addressed by https://github.com/weavejester/cljfmt/pull/183.
