### ISSUE TITLE
Unable to add more indentation hints

### ISSUE THREAD

**Issue by raysegantii** [weavejester/cljfmt#91]
I'd like to add a few preferences to the indentation, I put this in `~/.lein/profiles.lcj`:
```clojure
{:user {:cljfmt {:indents {send [[:block 1]]
                           assoc [[:block 1]]
                           update [[:block 1]]}}}}
```

But it still formats as:
```clojure
(send m assoc
      :key "value")
```
instead of
```clojure
(send m assoc
  :key "value")
```

Any idea please?

**Comment by weavejester** [comment]
Check the information in the README about `:block`:

> A `:block` rule is a little smarter. This will act like an inner indent only if there's a line break before a certain number of arguments, otherwise it acts like a normal list form.

So you've set `send` to `[:block 1]`, but you have a line break after the second argument, not the first. If you want the indentation to always be two characters, unconditionally, use `:inner`.

**Comment by or** [comment]
This probably is resolved.
