### ISSUE TITLE
remove-consecutive-blank-lines should remove between forms

### ISSUE THREAD

**Issue by bhurlow** [weavejester/cljfmt#92]
```clj
(  :foo :bar)
;; becomes
(:foo :bar)
```

but

```clj
(:foo   :bar)
;; space still remains
(:foo   :bar)
```

**Comment by bhurlow** [comment]
might to do with `count-newlines`

**Comment by weavejester** [comment]
`remove-consecutive-blank-lines` removes consecutive blank **lines**. It doesn't remove additional spaces within forms.

Sometimes additional spaces are used for alignment. cljfmt currently doesn't have a rule to differentiate between accidental spaces within forms, and spaces that are deliberately added.

**Comment by bhurlow** [comment]
Hence the word 'lines' :) thx

**Comment by lread** [comment]
@weavejester, I think this one can be closed.
