### ISSUE TITLE
Non-lein configurability

### ISSUE THREAD

**Issue by technomancy** [weavejester/cljfmt#93]
The readme mostly documents usage through the Leiningen plugin. It occurs to me that it would be nice to be able to invoke a formatting command directly from your editor, perhaps over an nrepl connection. However, if you're running `cljfmt` inside your project's process, it will not have access to the config map in `project.clj`.

Have you thought about allowing config options to be set somewhere on the classpath instead of inside `project.clj`?

I have an ulterior motive in asking this--I have a similar problem in Slamhound and some other tools, and I'm curious to hear your take on it.

**Comment by weavejester** [comment]
You can pass the options directly to `cljfmt.core/reformat-string`, so if you wanted you could do something like:

```clojure
(cljfmt.core/reformat-string code (read-string (System/getProperty "cljfmt.options"))
```

Though that doesn't include the diff formatting that I've added to the Leiningen plugin. It might be worth moving that into the cljfmt.core namespace or another library for ease of use.

If you're asking about a standard way of passing options from a Leiningen project file into a running REPL, I'm really not sure. Maybe Leiningen dumps the project map to a hidden cache directory, and includes the filepath via a system property. So something like:

```clojure
(read-string (slurp (System/getProperty "leiningen.project.cache")))
```

Would get you the project map that started the REPL. From there you could delve in and pull out the configuration.

Alternatively, maybe we need to allow project files to be specified as a data structure as well? A `project.edn` that would be the counterpart to `project.clj`. Then maybe have a small library to resolve profiles, and you'd have easy access to the project configuration.

**Comment by technomancy** [comment]
> If you're asking about a standard way of passing options from a
> Leiningen project file into a running REPL, I'm really not sure.

I would rather move towards decoupling them completely than adding a
mechanism to communicate between the two modes.

The bigger question is why this config is in the project.clj file to
begin with. I think there's a sense in which things get added to
project.clj because it's already there, and not because they necessarily
belong there. I've certainly been guilty of this myself.

There are a few things that run inside the project which need access to
the project map; for instance the test runner needs to know which
directories contain tests. But I would argue this is an exception rather
than a good default, and I think things like cljfmt would be much
better-served by an independent config file. What's the downside of just
reading from `dev-resources/cljfmt.clj` whether it's invoked from inside
the repl or from the lein task?

As you've mentioned, this can already be done by writing a wrapper
function, but I think it would be good to provide a convenience function
that reads the config from a predetermined location and document that.

Once config gets moved into the process, it may be possible for the
whole plugin to be replaced by a simple alias, and that `lein run -m
cljfmt.main` would be sufficient.

What do you think?

**Comment by weavejester** [comment]
I think I have a couple of reservations.

First, cljfmt statically analyses a source tree, so ideally you want to avoid loading in the project dependencies. The lein-cljfmt plugin currently doesn't require Leiningen starting another JVM, so there'd be a performance hit if it was changed to be an alias to `lein run -m cljfmt.main`. I guess you could maybe trampoline it?

Second, I don't really like the idea of having multiple configuration files. My work with Integrant and Duct have sold me on the idea of having one configuration structure or database. This allows broad queries and transformations of a project's structure. For example, you could apply some company-standard middleware over the configuration map that sets up a project's default formatting and linting rules.

The configuration doesn't necessarily have to be in the `project.clj` file, but I think moving toward separate configuration files is going in the wrong direction. I do think it would be useful to strip down lein-cljfmt and factor out the colourised diffs, but I don't think cljfmt should load in rules from a set resource path.

**Comment by technomancy** [comment]
> First, cljfmt statically analyses a source tree, so ideally you want
> to avoid loading in the project dependencies. The lein-cljfmt plugin
> currently doesn't require Leiningen starting another JVM, so there'd
> be a performance hit if it was changed to be an alias to lein run -m
> cljfmt.main. I guess you could maybe trampoline it?

I see; yeah performance is a concern. Trampoline won't work as an alias
because it requires cooperation from the bin/lein shell script.

> Second, I don't really like the idea of having multiple configuration
> files. My work with Integrant and Duct have sold me on the idea of
> having one configuration structure or database.

That makes sense to me for build-related things, but cljfmt strikes me
as being specifically an editor tool. It's not about "run this command
to prepare the project for deployment", it's about "here is another
command you can run during development to make changes to the source
code". It's a completely different category of tool from Duct or
Integrant. From my perspective (as I am not a user of cljfmt yet) it's
not about splitting up config from two files to one, but about porting
configuration from Elisp to Clojure.

It makes sense to me that it should be possible to run it from the
command-line, but for most workflows it would be very awkward to do
this. If I'm going to be reformatting my code, I'm going to write an
Emacs command to do it, and others would surely prefer to invoke it from
their editor of choice.

**Comment by weavejester** [comment]
What about this: we introduce a `cljfmt.main` namespace that includes a `--config` or `-c` option that allows a configuration file to be specified. This would allow cljfmt to be used as a standalone executable, without the need to tie the configuration to a fixed resource.

The lein-cljfmt plugin could just be a thin wrapper around it, effectively the same as an alias, but more performant because we can use Leiningen's JVM.

Another possibility is [node-cljfmt](https://github.com/snoe/node-cljfmt). I'm not sure if the dependencies are current, but since cljfmt runs under both Clojure and ClojureScript, it should be trivial to update. For use with an editor, this might work better because the startup time is lower.

It might even be worth folding node-cljfmt or something similar into cljfmt, so we'd have a cljfmt.main that could be executed in Clojure or ClojureScript. Might be some complication around the diff formatting, but for an editor presumably you wouldn't want that anyway.
